"""Generate corpus_schema_pg.sql from corpus_schema.sql (D2,
pg_corpus_harness_design.md).

The PG corpus schema is a GENERATED artifact, not a hand-maintained sibling —
the same discipline as pg_schema_cut.py: when the T-SQL schema of record
evolves, re-run this and the PG form follows; the two cannot drift silently.
FAIL-LOUD: any construct the rules don't recognize survives into the output
and trips the leftover audit at the end.

Rules (the established type map):
  NVARCHAR(n)/NVARCHAR(MAX)/VARCHAR(n) -> citext   BIT -> smallint
  DATETIME2 -> timestamp                            IDENTITY -> GENERATED
  AS (expr) PERSISTED -> <type> GENERATED ALWAYS AS (expr) STORED
  IF NOT EXISTS guards -> IF NOT EXISTS clauses     GO / SET QI / tail -> dropped
The client-side verification in create_corpus.py replaces the THROW/PRINT
tail on both engines ("verify rather than trust" — one verifier).

Usage: python corpus_schema_translate.py   (reads corpus_schema.sql beside it)
"""
import os
import re
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
SRC = os.path.join(HERE, "corpus_schema.sql")
OUT = os.path.join(HERE, "corpus_schema_pg.sql")

# explicit types for T-SQL computed columns (type is inferred there; PG
# GENERATED columns require one)
COMPUTED_TYPES = {
    "FinalCashCSF": "DECIMAL(18,2)",
    "FinalTotal": "DECIMAL(18,2)",
    # T-SQL INFERS computed-column types from the expression: DECIMAL(10,4)
    # divided by INT infers DECIMAL(21,15) (p = p1-s1+s2+max(6,s1+p2+1),
    # s = max(6,s1+p2+1)). The cross-engine gate caught a (10,4) guess
    # truncating what SQL Server stores at 15-scale.
    "AvgHouseholdSize": "DECIMAL(21,15)",
    "PersonCount": "INT",
}


def translate(text: str) -> str:
    out = text

    # header + schema creation
    out = re.sub(r"(?m)^SET QUOTED_IDENTIFIER ON;\s*$", "", out)
    out = re.sub(
        r"IF NOT EXISTS \(SELECT 1 FROM sys\.schemas WHERE name = 'v1'\)\s*\n\s*EXEC\('CREATE SCHEMA v1'\);",
        "CREATE SCHEMA IF NOT EXISTS v1;", out)

    # table guard blocks: IF NOT EXISTS (...sys.tables...) BEGIN ... END; ->
    # bare body with IF NOT EXISTS on the CREATEs
    out = re.sub(
        r"IF NOT EXISTS \(SELECT 1 FROM sys\.tables WHERE name = '\w+' AND schema_id = SCHEMA_ID\('v1'\)\)\s*\nBEGIN\n",
        "", out)
    out = re.sub(r"(?m)^END;\s*$", "", out)
    out = out.replace("CREATE TABLE v1.", "CREATE TABLE IF NOT EXISTS v1.")
    out = re.sub(r"(?m)^(\s*)CREATE (UNIQUE )?INDEX ",
                 r"\1CREATE \2INDEX IF NOT EXISTS ", out)

    # the property_units upgrade block (sys.columns guard -> ADD COLUMN IF NOT EXISTS)
    out = re.sub(
        r"IF NOT EXISTS \(SELECT 1 FROM sys\.columns\s*\n\s*WHERE object_id = OBJECT_ID\('v1\.property_units'\) AND name = 'AdjustedRent'\)\s*\n\s*ALTER TABLE v1\.property_units ADD AdjustedRent DECIMAL\(18,2\) NULL;",
        "ALTER TABLE v1.property_units ADD COLUMN IF NOT EXISTS AdjustedRent DECIMAL(18,2) NULL;",
        out)

    # verification tail (DECLARE ... THROW ... PRINT) -> dropped; client-side
    # verification in create_corpus.py is the single verifier on both engines
    out = re.sub(
        r"DECLARE @table_count INT;.*$",
        "-- (T-SQL verification tail dropped: create_corpus.py verifies\n"
        "--  table count + AdjustedRent client-side on both engines)\n", out, flags=re.S)

    # computed columns
    def computed(m):
        name, expr = m.group(1), m.group(2)
        ctype = COMPUTED_TYPES.get(name)
        if not ctype:
            raise SystemExit(f"computed column {name!r} has no type mapping — add it")
        return f"{name} {ctype} GENERATED ALWAYS AS ({expr}) STORED"
    out = re.sub(r"(\w+)\s+AS \((.+?)\) PERSISTED", computed, out)

    # types + identity (whitespace-tolerant — the source aligns columns)
    out = re.sub(r"\bINT\s+IDENTITY\(1,1\)", "INT GENERATED BY DEFAULT AS IDENTITY", out)
    out = re.sub(r"\bBIGINT\s+IDENTITY\(1,1\)", "BIGINT GENERATED BY DEFAULT AS IDENTITY", out)
    out = re.sub(r"\bNVARCHAR\(MAX\)", "citext", out)
    out = re.sub(r"\bNVARCHAR\(\d+\)", "citext", out)
    out = re.sub(r"\bVARCHAR\(\d+\)", "citext", out)
    out = re.sub(r"\bDATETIME2\b", "TIMESTAMP", out)
    out = re.sub(r"\bBIT\b", "SMALLINT", out)

    # GO batch separators
    out = re.sub(r"(?m)^GO\s*$", "", out)

    header = ("-- GENERATED by corpus_schema_translate.py from corpus_schema.sql —\n"
              "-- do not hand-edit; change the T-SQL source and re-run the translator.\n"
              "CREATE EXTENSION IF NOT EXISTS citext;\n")
    out = re.sub(r"\n{3,}", "\n\n", out)
    return header + out


def audit(pg_sql: str):
    """Leftover T-SQL constructs are a translation failure, not a warning."""
    lines = pg_sql.split("\n")
    leftovers = []
    for pat in (r"\bIDENTITY\(", r"\bNVARCHAR\b", r"\bDATETIME2\b", r"\bBIT\b",
                r"^GO\s*$", r"\bsys\.", r"\bTHROW\b", r"\bPRINT\b",
                r"\bDECLARE @", r"\bEXEC\(", r"\bPERSISTED\b", r"SCHEMA_ID"):
        for i, line in enumerate(lines, 1):
            if line.lstrip().startswith("--"):
                continue  # prose mentions in comments are not constructs
            if re.search(pat, line):
                leftovers.append(f"line {i}: {line.strip()[:90]}")
    if leftovers:
        raise SystemExit("T-SQL leftovers in translated output:\n  "
                         + "\n  ".join(leftovers))


if __name__ == "__main__":
    src = open(SRC, encoding="utf-8").read()
    pg_sql = translate(src)
    audit(pg_sql)
    with open(OUT, "w", encoding="utf-8", newline="\n") as f:
        f.write(pg_sql)
    tables = pg_sql.count("CREATE TABLE IF NOT EXISTS")
    print(f"written: {OUT} ({tables} tables)")
    if tables != 17:
        sys.exit(f"expected 17 tables, translated {tables} — investigate")
