"""Create a Liberty Bee corpus database from nothing.

Creates the database and applies `corpus_schema.sql` (the v1.* corpus schema of
record). After this, `regenerate_corpus.py` can populate it.

    python create_corpus.py --corpus LibertyBee_V2_Baseline
    python regenerate_corpus.py --corpus LibertyBee_V2_Baseline --scenario standard --seeds 1-200

A corpus is SINGLE-SCENARIO by design ('leg = DB') — one database per scenario,
rather than threading a Scenario column through seventeen tables. So a two-leg
sweep creates two corpora:

    python create_corpus.py --corpus LibertyBee_V2_Baseline
    python create_corpus.py --corpus LibertyBee_V2_DeepDiscount

Which scenario a corpus actually holds is recorded in `v1.corpus_meta` by the
sweep driver on first write, and enforced from then on.

Guard: refuses to rebuild a corpus that already holds runs unless --force,
because rebuilding drops the database.

Server and driver come from LB_SQL_SERVER / LB_SQL_DRIVER (default
localhost / ODBC Driver 17 for SQL Server), matching regenerate_corpus.py.

Recovery model: corpora are set to FULL. They are durable analysis artifacts,
not ephemeral scratch — a corpus represents days of compute and is expensive to
regenerate. If your instance runs a log/differential backup chain, take a full
backup immediately after creating a corpus so the chain has a base to build on;
without it, log and diff jobs have nothing to anchor to. With Ola Hallengren's
solution that is:

    EXECUTE dbo.DatabaseBackup @Databases = '<corpus_db>',
        @Directory = '<backup_dir>', @BackupType = 'FULL', @Compress = 'Y'

(Deliberately not invoked from here: a published tool should not assume any
particular backup solution is installed.)
"""

import argparse
import os
import re
import socket
import sys
from pathlib import Path

import pyodbc

# The script ships at the repository root; the schema sits beside it. Resolved
# relative to this file so the tool runs correctly from any working directory
# and from any checkout location — never hardcode a tree path here, or the tool
# silently binds itself to one machine's layout.
REPO = Path(os.path.dirname(os.path.abspath(__file__)))
SCHEMA_SQL = REPO / "corpus_schema.sql"
PG_SCHEMA_SQL = REPO / "corpus_schema_pg.sql"  # GENERATED by corpus_schema_translate.py

SQL_SERVER = os.environ.get("LB_SQL_SERVER", "localhost")
SQL_DRIVER = os.environ.get("LB_SQL_DRIVER", "ODBC Driver 17 for SQL Server")
CONN_TMPL = ("DRIVER={{" + SQL_DRIVER + "}};SERVER=" + SQL_SERVER
             + ";Trusted_Connection=yes;DATABASE={}")

PG_HOST = os.environ.get("LB_PG_HOST", "localhost")
PG_PORT = int(os.environ.get("LB_PG_PORT", "5432"))
PG_USER = os.environ.get("LB_PG_USER", "libertybee")  # password via pgpass.conf ONLY


def conn(db, autocommit=True):
    return pyodbc.connect(CONN_TMPL.format(db), timeout=60, autocommit=autocommit)


def run_batches(cur, sql_text):
    """Execute a T-SQL script split on GO batch separators (pyodbc has no
    batch parser; GO is a client directive, not T-SQL)."""
    for batch in re.split(r"(?im)^\s*GO\s*$", sql_text):
        batch = batch.strip()
        if batch:
            cur.execute(batch)


def existing_run_count(db):
    """Runs already in the corpus: -1 if the database does not exist, 0 if it
    exists without a populated v1.run_summary."""
    with conn("master") as c:
        cur = c.cursor()
        if cur.execute("SELECT DB_ID(?)", (db,)).fetchone()[0] is None:
            return -1
        try:
            return cur.execute(f"SELECT COUNT(*) FROM [{db}].v1.run_summary").fetchone()[0]
        except pyodbc.Error:
            return 0


def pg_conn(dbname="postgres", autocommit=True):
    import psycopg
    return psycopg.connect(host=PG_HOST, port=PG_PORT, user=PG_USER,
                           dbname=dbname, autocommit=autocommit)


def pg_existing_run_count(db):
    with pg_conn() as c:
        if not c.execute("SELECT 1 FROM pg_database WHERE datname = %s",
                         (db,)).fetchone():
            return -1
    try:
        with pg_conn(db) as c:
            return c.execute("SELECT COUNT(*) FROM v1.run_summary").fetchone()[0]
    except Exception:
        return 0


def pg_create(db, force):
    """The PG corpus path (D2, pg_corpus_harness_design.md). Recovery model:
    PG WAL is cluster-level, so the durable-artifact policy is operational —
    take a pg_dump after each sweep (RUNBOOK) — rather than DDL."""
    if not PG_SCHEMA_SQL.is_file():
        sys.exit(f"FATAL: {PG_SCHEMA_SQL} missing — generate it: "
                 f"python corpus_schema_translate.py")
    existing = pg_existing_run_count(db)
    if existing > 0 and not force:
        sys.exit(f"REFUSING: [{db}] already holds {existing} runs — rebuilding would "
                 f"drop the database and destroy them.\n"
                 f"          Pass --force if that is genuinely what you want.")
    if existing > 0:
        print(f"WARNING: --force given; destroying [{db}] and its {existing} runs.", flush=True)
    with pg_conn() as c:
        if existing >= 0:
            c.execute(f"DROP DATABASE IF EXISTS {db}")
        c.execute(f"CREATE DATABASE {db}")
    print(f"created [{db}] on {PG_HOST}:{PG_PORT}")
    with pg_conn(db) as c:
        c.execute(PG_SCHEMA_SQL.read_text(encoding="utf-8"))
    # Verify rather than trust — the ONE verifier for both engines
    # (the T-SQL THROW tail was dropped at translation).
    with pg_conn(db) as c:
        tables = c.execute(
            "SELECT COUNT(*) FROM information_schema.tables "
            "WHERE table_schema = 'v1' AND table_type = 'BASE TABLE'").fetchone()[0]
        has_adj = c.execute(
            "SELECT COUNT(*) FROM information_schema.columns "
            "WHERE table_schema = 'v1' AND table_name = 'property_units' "
            "AND column_name = 'adjustedrent'").fetchone()[0]
        has_meta = c.execute(
            "SELECT COUNT(*) FROM information_schema.tables "
            "WHERE table_schema = 'v1' AND table_name = 'corpus_meta'").fetchone()[0]
    ok = tables == 17 and has_adj and has_meta
    print(f"[{db}] ready on {socket.gethostname()}: {tables} v1.* tables, "
          f"AdjustedRent={'yes' if has_adj else 'NO'}, corpus_meta={'yes' if has_meta else 'NO'}")
    if not ok:
        sys.exit("FATAL: corpus schema verification failed (see counts above).")
    print(f"\nNext: python regenerate_corpus.py --corpus {db} --scenario <scenario> --seeds <range>")
    print("Reminder: a corpus is a durable artifact — take a pg_dump after each "
          "sweep completes (see RUNBOOK).")
    sys.exit(0)


def main():
    ap = argparse.ArgumentParser(
        description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--corpus", required=True, help="corpus database name to create")
    ap.add_argument("--force", action="store_true",
                    help="rebuild even if the corpus already holds runs (drops the database)")
    ap.add_argument("--pg", action="store_true",
                    help="deprecated no-op: PostgreSQL is the default")
    ap.add_argument("--mssql", action="store_true",
                    help="create the corpus on SQL Server (pre-cutover legacy path)")
    args = ap.parse_args()
    db = args.corpus

    if not args.mssql:
        lowered = db.lower()
        if lowered != db:
            print(f"note: PG folds unquoted names to lowercase — using [{lowered}]")
            db = lowered
        pg_create(db, args.force)
        return

    if not SCHEMA_SQL.is_file():
        sys.exit(f"FATAL: corpus schema not found at {SCHEMA_SQL}\n"
                 f"       create_corpus.py must sit beside corpus_schema.sql at the repo root.")

    existing = existing_run_count(db)
    if existing > 0 and not args.force:
        sys.exit(f"REFUSING: [{db}] already holds {existing} runs — rebuilding would "
                 f"drop the database and destroy them.\n"
                 f"          Pass --force if that is genuinely what you want.")
    if existing > 0:
        print(f"WARNING: --force given; destroying [{db}] and its {existing} runs.", flush=True)

    with conn("master") as c:
        cur = c.cursor()
        cur.execute(f"IF DB_ID('{db}') IS NOT NULL "
                    f"BEGIN ALTER DATABASE [{db}] SET SINGLE_USER WITH ROLLBACK IMMEDIATE; "
                    f"DROP DATABASE [{db}]; END")
        cur.execute(f"CREATE DATABASE [{db}]")
        # Durable artifact, not scratch — never SIMPLE.
        cur.execute(f"ALTER DATABASE [{db}] SET RECOVERY FULL")
    print(f"created [{db}] on {SQL_SERVER} (recovery FULL)")

    with conn(db) as c:
        run_batches(c.cursor(), SCHEMA_SQL.read_text(encoding="utf-8"))

    # Verify rather than trust: the schema script's own THROW guards cover table
    # count and AdjustedRent, but confirm from the client side too.
    with conn(db) as c:
        cur = c.cursor()
        tables = cur.execute(
            "SELECT COUNT(*) FROM sys.tables WHERE schema_id = SCHEMA_ID('v1')").fetchone()[0]
        has_adj = cur.execute(
            "SELECT COUNT(*) FROM sys.columns WHERE object_id = OBJECT_ID('v1.property_units') "
            "AND name = 'AdjustedRent'").fetchone()[0]
        has_meta = cur.execute(
            "SELECT COUNT(*) FROM sys.tables WHERE name = 'corpus_meta' "
            "AND schema_id = SCHEMA_ID('v1')").fetchone()[0]

    ok = tables == 17 and has_adj and has_meta
    print(f"[{db}] ready on {socket.gethostname()}: {tables} v1.* tables, "
          f"AdjustedRent={'yes' if has_adj else 'NO'}, corpus_meta={'yes' if has_meta else 'NO'}")
    if not ok:
        sys.exit("FATAL: corpus schema verification failed (see counts above).")
    print(f"\nNext: python regenerate_corpus.py --corpus {db} --scenario <scenario> --seeds <range>")
    print("Reminder: if this instance runs a log/diff backup chain, take a FULL backup "
          "of the corpus now so the chain has a base to build on.")
    sys.exit(0)


if __name__ == "__main__":
    main()
