-- Generated by pg_schema_cut.py — the PG baseline of record
-- Source: the SQL Server catalog through the current migration chain
CREATE EXTENSION IF NOT EXISTS citext;

-- T-SQL date-function compatibility shims: the regression suite (and
-- adopter SQL) uses YEAR()/MONTH()/DATEFROMPARTS()/EOMONTH(), which PG
-- lacks. PG happily hosts functions with these names — four IMMUTABLE
-- one-liners erase the whole dialect class. date-typed args only (the
-- engine's date columns); T-SQL semantics preserved exactly.
CREATE OR REPLACE FUNCTION year(d date) RETURNS int
    LANGUAGE sql IMMUTABLE AS 'SELECT EXTRACT(YEAR FROM d)::int';
CREATE OR REPLACE FUNCTION month(d date) RETURNS int
    LANGUAGE sql IMMUTABLE AS 'SELECT EXTRACT(MONTH FROM d)::int';
CREATE OR REPLACE FUNCTION day(d date) RETURNS int
    LANGUAGE sql IMMUTABLE AS 'SELECT EXTRACT(DAY FROM d)::int';
CREATE OR REPLACE FUNCTION datefromparts(y int, m int, dd int) RETURNS date
    LANGUAGE sql IMMUTABLE AS 'SELECT make_date(y, m, dd)';
CREATE OR REPLACE FUNCTION eomonth(d date) RETURNS date
    LANGUAGE sql IMMUTABLE AS
    $$SELECT (date_trunc('month', d) + INTERVAL '1 month' - INTERVAL '1 day')::date$$;

CREATE SCHEMA IF NOT EXISTS reference;
CREATE SCHEMA IF NOT EXISTS simulation;
CREATE SCHEMA IF NOT EXISTS dbo;

CREATE TABLE dbo._provenance (
    Label citext,
    CreatedUtc timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CreatedBy citext,
    SourceBranch citext,
    SourceCommit citext,
    MigrationsScratch smallint NOT NULL DEFAULT 0,
    Note citext
);

CREATE TABLE dbo.SchemaVersion (
    Version citext NOT NULL,
    Description citext,
    ScriptPath citext,
    AppliedAt timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    AppliedBy citext NOT NULL DEFAULT CURRENT_USER
);

CREATE TABLE reference.AcquisitionParameters (
    ParameterID integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    OfferStrategyBelowAskPct numeric(5,4) NOT NULL DEFAULT 0.0500,
    OfferStrategyAtAskPct numeric(5,4) NOT NULL DEFAULT 0.0000,
    OfferStrategyPremiumPct numeric(5,4) NOT NULL DEFAULT 0.0200,
    OfferStrategyBelowAskWeight numeric(5,4) NOT NULL DEFAULT 0.60,
    OfferStrategyAtAskWeight numeric(5,4) NOT NULL DEFAULT 0.30,
    OfferStrategyPremiumWeight numeric(5,4) NOT NULL DEFAULT 0.10,
    SellerAcceptanceProbability numeric(5,4) NOT NULL DEFAULT 0.50,
    SellerCounterProbability numeric(5,4) NOT NULL DEFAULT 0.30,
    SellerRejectionProbability numeric(5,4) NOT NULL DEFAULT 0.20,
    SellerCounterIncreasePct numeric(5,4) NOT NULL DEFAULT 0.03,
    InspectionCleanProbability numeric(5,4) NOT NULL DEFAULT 0.20,
    InspectionMinorProbability numeric(5,4) NOT NULL DEFAULT 0.50,
    InspectionModerateProbability numeric(5,4) NOT NULL DEFAULT 0.20,
    InspectionMajorProbability numeric(5,4) NOT NULL DEFAULT 0.10,
    InspectionCostMin numeric(10,2) NOT NULL DEFAULT 500.00,
    InspectionCostMax numeric(10,2) NOT NULL DEFAULT 1500.00,
    LBWithdrawalThresholdPct numeric(5,4) NOT NULL DEFAULT 0.0800,
    PriceReductionProbability numeric(5,4) NOT NULL DEFAULT 0.50,
    SellerRepairsProbability numeric(5,4) NOT NULL DEFAULT 0.30,
    NoConcesssProbability numeric(5,4) NOT NULL DEFAULT 0.20,
    ClosingDelayDaysMin integer NOT NULL DEFAULT 30,
    ClosingDelayDaysMax integer NOT NULL DEFAULT 60,
    ClosingCostsPct numeric(5,4) NOT NULL DEFAULT 0.0300,
    SellerRepairDelayDaysMin integer NOT NULL DEFAULT 7,
    SellerRepairDelayDaysMax integer NOT NULL DEFAULT 30,
    MaxConcurrentPipelines_Base integer NOT NULL DEFAULT 3,
    MaxConcurrentPipelines_RampMultiplier numeric(5,4) NOT NULL DEFAULT 2.0,
    Timeout_OfferResponse_MaxDays integer NOT NULL DEFAULT 10,
    Timeout_InspectionScheduling_MaxDays integer NOT NULL DEFAULT 14,
    Timeout_Negotiation_MaxDays integer NOT NULL DEFAULT 21,
    Timeout_Closing_MaxDays integer NOT NULL DEFAULT 90,
    SellerResponseDelayDaysMin integer NOT NULL DEFAULT 1,
    SellerResponseDelayDaysMax integer NOT NULL DEFAULT 5,
    InspectionSchedulingDelayMin integer NOT NULL DEFAULT 3,
    InspectionSchedulingDelayMax integer NOT NULL DEFAULT 7,
    NegotiationDelayDaysMin integer NOT NULL DEFAULT 2,
    NegotiationDelayDaysMax integer NOT NULL DEFAULT 7,
    CreatedAt timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UpdatedAt timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    Notes citext
);

CREATE TABLE reference.ComplianceParameters (
    ParameterID integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    WorkType citext NOT NULL,
    CostMin numeric(18,2) NOT NULL,
    CostMax numeric(18,2) NOT NULL,
    DurationMinDays integer NOT NULL,
    DurationMaxDays integer NOT NULL,
    FailChanceBase numeric(5,4) NOT NULL,
    PassChanceOverride numeric(5,4),
    ContractorLagMinDays integer NOT NULL,
    ContractorLagMaxDays integer NOT NULL,
    IsBlockingDefault smallint NOT NULL,
    ScopeType citext NOT NULL,
    Description citext
);

CREATE TABLE reference.EmployeeRole (
    RoleID integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    Role citext NOT NULL,
    BaseSalary numeric(18,0) NOT NULL,
    SalaryCap numeric(18,0) NOT NULL,
    BenefitsCost numeric(18,0) NOT NULL
);

CREATE TABLE reference.FirstName (
    FirstNameID integer NOT NULL,
    FirstName citext NOT NULL,
    Gender citext
);

CREATE TABLE reference.LastName (
    LastNameID integer NOT NULL,
    LastName citext NOT NULL
);

CREATE TABLE reference.MedianRentData (
    Category citext,
    Subcategory citext,
    Bedrooms citext,
    MedianRent citext,
    Source citext
);

CREATE TABLE reference.ParameterCategory (
    Category citext NOT NULL,
    Description citext NOT NULL,
    DisplayOrder integer NOT NULL
);

CREATE TABLE reference.ParameterRegistryDefault (
    Category citext NOT NULL,
    Name citext NOT NULL,
    Value citext NOT NULL,
    DataType citext NOT NULL,
    Description citext,
    Scope citext NOT NULL DEFAULT 'model'
);

CREATE TABLE reference.ParameterRegistryDefined (
    ProjectionID integer NOT NULL,
    Category citext NOT NULL,
    Name citext NOT NULL,
    Value citext NOT NULL,
    DataType citext NOT NULL,
    Description citext
);

CREATE TABLE reference.PersonSeed (
    SeedPersonID integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    SeedFamilyID integer NOT NULL,
    GenerationDepth smallint NOT NULL,
    FirstName citext NOT NULL,
    LastName citext NOT NULL,
    BirthDate date NOT NULL,
    Sex citext,
    Notes citext,
    CreatedAtUtc timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE reference.PersonSeedRelationship (
    SeedPersonRelationshipID integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    SeedFamilyID integer NOT NULL,
    SeedPersonID integer NOT NULL,
    RelatedSeedPersonID integer NOT NULL,
    RelationshipType citext NOT NULL,
    StartDate date,
    EndDate date,
    CreatedAtUtc timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE reference.Projection (
    ProjectionID integer NOT NULL,
    Name citext NOT NULL,
    Description citext,
    Kind citext NOT NULL,
    ScenarioTag citext NOT NULL,
    CreatedOn timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE reference.Properties (
    PropertyID integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    Source citext NOT NULL,
    SourceID integer,
    PropertyAddress citext,
    City citext,
    State citext,
    Zip citext,
    LivingArea integer,
    PropertyStyle citext,
    YearBuilt integer,
    LotSize numeric(18,4),
    LotSizeUnit citext,
    TotalUnits integer,
    ReconciliationSource citext,
    ReconciliationConfidence numeric(3,2),
    CreatedAt timestamp DEFAULT CURRENT_TIMESTAMP,
    BasePrice numeric(18,2),
    Town citext
);

CREATE TABLE reference.SeedFamily (
    SeedFamilyID integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    FamilyLabel citext,
    GenerationDepthMax smallint NOT NULL DEFAULT 1,
    Notes citext,
    CreatedAtUtc timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE reference.Tenants (
    FullName citext NOT NULL,
    TenantRowID integer GENERATED BY DEFAULT AS IDENTITY NOT NULL
);

CREATE TABLE reference.TownParameterOverride (
    Town citext NOT NULL,
    Category citext NOT NULL,
    Name citext NOT NULL,
    Value citext NOT NULL,
    Source citext,
    UpdatedAtUtc timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE reference.Units (
    UnitID integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    PropertyID integer NOT NULL,
    UnitNumber citext NOT NULL,
    Beds integer NOT NULL,
    Baths numeric(3,2) NOT NULL,
    BaseRent numeric(10,2),
    AdjustedRent numeric(10,2),
    CreatedAt timestamp DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE simulation.ApplicantEvaluation (
    RunID bigint NOT NULL,
    EvaluationID integer NOT NULL,
    VacancyID integer NOT NULL,
    ApplicantIndex integer NOT NULL,
    HouseholdType citext NOT NULL,
    HouseholdIncomeBand citext NOT NULL,
    AdultCount integer NOT NULL,
    ChildCount integer NOT NULL,
    Outcome citext NOT NULL,
    RejectionReason citext,
    EvaluatedDate date NOT NULL
);

CREATE TABLE simulation.ComplianceAttempt (
    RunID bigint NOT NULL,
    AttemptID integer NOT NULL,
    PropertyID integer NOT NULL,
    ScopeType citext NOT NULL,
    TriggerType citext NOT NULL,
    UnitID integer,
    StartDate date NOT NULL,
    CompletedDate date,
    IsActive smallint NOT NULL DEFAULT 1,
    NextActionDate date,
    BuildingOnlineDate date,
    UnitReadyDate date
);

CREATE TABLE simulation.ComplianceStep (
    RunID bigint NOT NULL,
    StepID integer NOT NULL,
    AttemptID integer NOT NULL,
    WorkItemID integer,
    StepType citext NOT NULL,
    EffectiveDate date NOT NULL,
    Notes citext,
    EventID bigint NOT NULL
);

CREATE TABLE simulation.ComplianceWorkItem (
    RunID bigint NOT NULL,
    WorkItemID integer NOT NULL,
    AttemptID integer NOT NULL,
    PropertyID integer NOT NULL,
    UnitID integer,
    WorkType citext NOT NULL,
    Status citext NOT NULL,
    ScheduledDate date NOT NULL,
    StartDate date,
    CompletedDate date,
    CostEstimate numeric(18,2) NOT NULL,
    ActualCost numeric(18,2),
    PaidDate date,
    DurationDays integer,
    ParentWorkItemID integer,
    Severity citext,
    Metadata citext
);

CREATE TABLE simulation.Employees (
    RunID bigint NOT NULL,
    EmployeeID integer NOT NULL,
    RoleID integer NOT NULL,
    HiredDate date NOT NULL,
    TerminatedDate date,
    BaseSalary numeric(18,4) NOT NULL,
    BenefitsCost numeric(18,4) NOT NULL,
    IsActive smallint NOT NULL DEFAULT 1
);

CREATE TABLE simulation.Event (
    RunID bigint NOT NULL,
    EventID bigint NOT NULL,
    MonthIndex integer NOT NULL,
    EffectiveDate date NOT NULL,
    LoggedAt timestamp NOT NULL,
    EventType citext NOT NULL,
    EntityType citext,
    EntityID bigint,
    ActionType citext,
    Amount numeric(18,2),
    Currency citext,
    CausalTag citext,
    Metadata citext
);

CREATE TABLE simulation.FundLedger (
    RunID bigint NOT NULL,
    EventID bigint NOT NULL,
    LedgerDate date NOT NULL,
    CashDebit numeric(14,2) NOT NULL DEFAULT 0,
    CashCredit numeric(14,2) NOT NULL DEFAULT 0,
    CashBalance numeric(14,2) NOT NULL DEFAULT 0,
    CSFDebit numeric(14,2) NOT NULL DEFAULT 0,
    CSFCredit numeric(14,2) NOT NULL DEFAULT 0,
    CSFBalance numeric(14,2) NOT NULL DEFAULT 0,
    EIPDebit numeric(14,2) NOT NULL DEFAULT 0,
    EIPCredit numeric(14,2) NOT NULL DEFAULT 0,
    EIPBalance numeric(14,2) NOT NULL DEFAULT 0,
    CashHoldCredit numeric(12,2) NOT NULL DEFAULT 0,
    CashHoldDebit numeric(12,2) NOT NULL DEFAULT 0,
    CashHoldBalance numeric(12,2) NOT NULL DEFAULT 0,
    EscrowDebit numeric(14,2) NOT NULL DEFAULT 0.00,
    EscrowCredit numeric(14,2) NOT NULL DEFAULT 0.00,
    EscrowBalance numeric(14,2) NOT NULL DEFAULT 0.00
);

CREATE TABLE simulation.GrantLedger (
    RunID bigint NOT NULL,
    EventID bigint NOT NULL,
    MonthIndex integer NOT NULL,
    GrantType citext NOT NULL,
    Status citext NOT NULL,
    Amount numeric(14,2),
    ApplicationDate date NOT NULL,
    DecisionDate date
);

CREATE TABLE simulation.Household (
    RunID bigint NOT NULL,
    HouseholdID integer NOT NULL,
    HouseholdType citext NOT NULL,
    HouseholdIncomeBand citext NOT NULL,
    AdultCount integer NOT NULL,
    ChildCount integer NOT NULL,
    CreatedDate date NOT NULL,
    CreatedEventID bigint NOT NULL,
    TCSRedemptionProbability numeric(5,4) NOT NULL DEFAULT 0.0200,
    TCSRedemptionProbabilityUpdatedDate date,
    SigningMonthlyIncome numeric(10,2)
);

CREATE TABLE simulation.InflationSchedule (
    RunID bigint NOT NULL,
    MonthIndex integer NOT NULL,
    InflationDate date NOT NULL,
    GeneralRate numeric(9,6) NOT NULL,
    RentRate numeric(9,6) NOT NULL,
    OpExRate numeric(9,6) NOT NULL,
    PropertyRate numeric(9,6) NOT NULL,
    ScenarioType citext NOT NULL,
    ScenarioPhase citext,
    Notes citext,
    VacancyDelta numeric(6,4) NOT NULL DEFAULT 0,
    WageGrowthRate numeric(9,6) NOT NULL DEFAULT 0
);

CREATE TABLE simulation.Lease (
    RunID bigint NOT NULL,
    LeaseID integer NOT NULL,
    HouseholdID integer NOT NULL,
    UnitID integer NOT NULL,
    VacancyID integer NOT NULL,
    LeaseSignedDate date NOT NULL,
    LeaseStartDate date NOT NULL,
    LeaseEndDate date NOT NULL,
    MonthlyRent numeric(10,2) NOT NULL,
    LeaseStatus citext NOT NULL,
    SignedEventID bigint NOT NULL,
    ConsecutiveMissedPayments integer NOT NULL DEFAULT 0,
    LastPaymentDate date,
    RenewalDecision citext,
    RenewalDecidedDate date,
    CumulativeRentReductionPct numeric(5,4) NOT NULL DEFAULT 0,
    EffectiveMonthlyRent numeric(10,2) NOT NULL
);

CREATE TABLE simulation.LeaseDeposit (
    RunID bigint NOT NULL,
    LeaseID integer NOT NULL,
    DepositRequiredAmount numeric(18,2) NOT NULL,
    DepositEscrowedAmount numeric(18,2) NOT NULL DEFAULT 0.00,
    DepositMethod citext NOT NULL,
    InstallmentsPlanned integer NOT NULL DEFAULT 4,
    InstallmentsPaidCount integer NOT NULL DEFAULT 0,
    DepositFundedDate date,
    Status citext NOT NULL DEFAULT 'ACTIVE',
    CreatedAt timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UpdatedAt timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    SettlementStatus citext,
    SettlementDueDate date,
    DamageAmount numeric(10,2),
    SettlementOutcome citext
);

CREATE TABLE simulation.LeaseDepositLedger (
    RunID bigint NOT NULL,
    LedgerID bigint NOT NULL,
    LeaseID integer NOT NULL,
    TxnDate date NOT NULL,
    TxnType citext NOT NULL,
    Amount numeric(18,2) NOT NULL,
    BalanceAfter numeric(18,2) NOT NULL,
    EventID bigint,
    Notes citext,
    CreatedAt timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE simulation.LeaseTermination (
    RunID bigint NOT NULL,
    LeaseID integer NOT NULL,
    TerminationType citext NOT NULL,
    TerminationDate date NOT NULL,
    TerminationReason citext,
    ArrearsAtExit numeric(18,2) NOT NULL DEFAULT 0.00,
    DepositWithheldAmount numeric(18,2) NOT NULL DEFAULT 0.00,
    DepositForfeited smallint NOT NULL DEFAULT 0,
    EarlyBreakPenalty numeric(18,2),
    EvictionFiledDate date,
    EvictionExecutionDate date,
    DepositSettlementDate date,
    DepositReturnDate date,
    TurnoverStartDate date,
    TurnoverEndDate date,
    VacancyCreatedDate date,
    CreatedAt timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE simulation.LeaseTerminationLedger (
    RunID bigint NOT NULL,
    LedgerID bigint NOT NULL,
    LeaseID integer NOT NULL,
    EventID bigint NOT NULL,
    TxnDate date NOT NULL,
    TxnType citext NOT NULL,
    Description citext,
    Amount numeric(18,2),
    Metadata citext,
    CreatedAt timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE simulation.MonthlyPaymentStatus (
    RunID bigint NOT NULL,
    LeaseID integer NOT NULL,
    BillingMonth date NOT NULL,
    CanPayThisMonth smallint NOT NULL,
    PaymentDueDate date NOT NULL,
    GracePeriodEndDate date NOT NULL,
    ActualPaymentDate date,
    PaymentStatus citext,
    LateFeeAmount numeric(10,2),
    AmountDue numeric(10,2) NOT NULL,
    ArrearsAmount numeric(10,2) NOT NULL DEFAULT 0
);

CREATE TABLE simulation.Payroll (
    RunID bigint NOT NULL,
    EventID bigint NOT NULL,
    PayrollID integer NOT NULL,
    PayrollDate date NOT NULL,
    EmployeeID integer NOT NULL,
    GrossPay numeric(18,4) NOT NULL,
    BenefitsCost numeric(18,4) NOT NULL,
    TotalCost numeric(18,4) NOT NULL
);

CREATE TABLE simulation.Person (
    RunID bigint NOT NULL,
    PersonID integer NOT NULL,
    HouseholdID integer NOT NULL,
    FirstName citext NOT NULL,
    LastName citext NOT NULL,
    DateOfBirth date NOT NULL,
    IsAdult smallint NOT NULL,
    CreatedDate date NOT NULL,
    CreatedEventID bigint NOT NULL
);

CREATE TABLE simulation.Properties (
    RunID bigint NOT NULL,
    EventID bigint NOT NULL,
    PropertyID integer NOT NULL,
    AddressID integer NOT NULL,
    ADDRESS citext NOT NULL,
    PROPERTYTYPE citext NOT NULL,
    AcquisitionDate date NOT NULL,
    BasePrice numeric(14,2) NOT NULL,
    InflationAdjustedPrice numeric(14,2) NOT NULL,
    TotalUnits integer NOT NULL
);

CREATE TABLE simulation.PropertyAcquisitionAttempt (
    RunID bigint NOT NULL,
    AttemptID integer NOT NULL,
    PropertyID integer NOT NULL,
    OfferDate date NOT NULL,
    ListingPrice numeric(12,2) NOT NULL,
    OfferAmount numeric(12,2),
    OfferStrategy citext,
    SellerResponse citext,
    CounterAmount numeric(12,2),
    LBResponseToCounter citext,
    InspectionDate date,
    InspectionSeverity citext,
    InspectionCost numeric(12,2),
    EstimatedRepairCost numeric(12,2),
    InspectionFlags citext,
    NegotiationOutcome citext,
    AdjustedPurchasePrice numeric(12,2),
    SellerRepairList citext,
    SellerRepairDelayDays integer,
    ClosingDate date,
    FinalPurchasePrice numeric(12,2),
    ClosingCosts numeric(12,2),
    ClosingDelayDays integer,
    AcquisitionSucceeded smallint NOT NULL DEFAULT 0,
    WithdrawalReason citext,
    FailureReason citext,
    PipelineStage citext NOT NULL DEFAULT 'MakingOffer',
    IsActive smallint NOT NULL DEFAULT 1,
    StageEnteredDate date NOT NULL,
    NextActionDate date,
    StageTimeoutDate date,
    CreatedAt timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    LastUpdatedDate timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    AssessedLeadCost numeric(18,2),
    LeadAssessed smallint NOT NULL DEFAULT 0
);

CREATE TABLE simulation.PropertyAcquisitionStep (
    RunID bigint NOT NULL,
    AttemptID integer NOT NULL,
    StepID integer NOT NULL,
    EffectiveDate date NOT NULL,
    EventID bigint NOT NULL,
    StepType citext NOT NULL,
    Amount numeric(18,2),
    Notes citext
);

CREATE TABLE simulation.PropertyMarket (
    RunID bigint NOT NULL,
    PropertyMarketID bigint NOT NULL,
    PropertyID integer NOT NULL,
    MarketStatus citext NOT NULL,
    EffectiveDate date NOT NULL,
    ExpirationDate date,
    ExpectedReturnDate date,
    CurrentListingPrice numeric(15,2),
    OriginalBasePrice numeric(15,2),
    DaysOnMarket integer,
    HoldPeriodDays integer,
    LastOwnerType citext
);

CREATE TABLE simulation.PropertyUnits (
    RunID bigint NOT NULL,
    UnitID integer NOT NULL,
    PropertyID integer NOT NULL,
    Unit citext NOT NULL,
    Beds numeric(3,1) NOT NULL,
    Baths numeric(3,1) NOT NULL,
    BaseRent numeric(8,2) NOT NULL,
    IsOccupied smallint NOT NULL DEFAULT 0,
    EventID bigint NOT NULL,
    UnitStatus citext DEFAULT 'Available',
    CurrentLeaseID integer,
    TurnoverStartDate date,
    TurnoverEndDate date,
    AdjustedRent numeric(8,2)
);

CREATE TABLE simulation.RentCollection (
    RunID bigint NOT NULL,
    CollectionID integer NOT NULL,
    LeaseID integer NOT NULL,
    CollectionDate date NOT NULL,
    CollectionMonth date NOT NULL,
    AmountCollected numeric(10,2) NOT NULL,
    CreatedEventID bigint NOT NULL,
    PaymentStatus citext,
    IsLate smallint NOT NULL DEFAULT 0,
    LateFeeAmount numeric(10,2) NOT NULL DEFAULT 0.00,
    PaymentDueDate date,
    ActualPaymentDate date,
    ArrearsAmount numeric(10,2) NOT NULL DEFAULT 0.00
);

CREATE TABLE simulation.Run (
    RunID bigint NOT NULL,
    ProjectionID integer,
    StartDate date NOT NULL,
    EndDate date NOT NULL,
    Status citext NOT NULL,
    CreatedAt timestamp,
    CompletedAt timestamp,
    RandomSeed integer,
    Notes citext,
    RunType citext,
    SnapshotCadence citext
);

CREATE TABLE simulation.RunSnapshot (
    RunID bigint NOT NULL,
    SnapshotDate date NOT NULL,
    MonthIndex integer NOT NULL,
    SnapshotCadence citext NOT NULL,
    SnapshotSource citext NOT NULL,
    CashBalance numeric(18,2) NOT NULL,
    CSFBalance numeric(18,2) NOT NULL,
    EIPBalance numeric(18,2) NOT NULL,
    EscrowBalance numeric(18,2) NOT NULL,
    TotalFundBalance numeric(18,2) NOT NULL,
    PropertiesOwned integer NOT NULL,
    UnitsTotal integer NOT NULL,
    UnitsOccupied integer NOT NULL,
    UnitsVacant integer NOT NULL,
    UnitsInTurnover integer NOT NULL,
    OccupancyRate numeric(9,6) NOT NULL,
    VacancyRate numeric(9,6) NOT NULL,
    ActiveLeases integer NOT NULL,
    MonthRentCollected numeric(18,2) NOT NULL,
    MonthOpEx numeric(18,2) NOT NULL,
    MonthPayroll numeric(18,2) NOT NULL,
    EmployeesActive integer NOT NULL,
    TerminationsCumulative integer NOT NULL,
    EvictionsCumulative integer NOT NULL,
    TurnoversCompleted integer NOT NULL,
    SnapshotCreatedAt timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE simulation.TenantCreditBalance (
    RunID bigint NOT NULL,
    HouseholdID integer NOT NULL,
    CurrentBalance numeric(10,2) NOT NULL DEFAULT 0,
    LifetimeAccrued numeric(10,2) NOT NULL DEFAULT 0,
    LifetimeRedeemed numeric(10,2) NOT NULL DEFAULT 0,
    LastAccrualDate date,
    LastUpdatedEventID bigint,
    AnnualRedemptionUsed numeric(10,2) NOT NULL DEFAULT 0,
    LastRedemptionYear integer,
    SystemExitDate date,
    ExpiryStatus citext,
    CreditExpiryDate date
);

CREATE TABLE simulation.TenantCreditLedger (
    RunID bigint NOT NULL,
    CreditTransactionID integer NOT NULL,
    HouseholdID integer NOT NULL,
    TransactionDate date NOT NULL,
    TransactionType citext NOT NULL,
    Amount numeric(10,2) NOT NULL,
    BalanceAfter numeric(10,2) NOT NULL,
    RelatedCollectionID integer,
    RelatedLeaseID integer,
    CreatedEventID bigint NOT NULL,
    Notes citext
);

CREATE TABLE simulation.Tenants (
    RunID integer NOT NULL,
    EventID bigint,
    TenantID integer NOT NULL,
    TenantName citext NOT NULL,
    MoveInDate date NOT NULL,
    MoveOutDate date,
    HouseholdSize integer NOT NULL DEFAULT 1,
    IncomeLevel citext NOT NULL,
    CreditScore integer,
    IsActive smallint NOT NULL DEFAULT 1
);

CREATE TABLE simulation.TurnoverWorkOrder (
    RunID bigint NOT NULL,
    TurnoverWorkOrderID integer NOT NULL,
    LeaseID integer NOT NULL,
    UnitID integer NOT NULL,
    PropertyID integer,
    TerminationType citext NOT NULL,
    WorkItemType citext NOT NULL,
    WorkSequence integer NOT NULL,
    Status citext NOT NULL,
    RequiredFlag smallint NOT NULL,
    ScheduledStartDate date,
    ScheduledEndDate date,
    ActualStartDate date,
    ActualEndDate date,
    DurationDays integer NOT NULL,
    WasEviction smallint NOT NULL,
    DamageWithheldAmount numeric(18,2),
    EventID bigint,
    CreatedAt timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UpdatedAt timestamp
);

CREATE TABLE simulation.Vacancy (
    RunID bigint NOT NULL,
    VacancyID integer NOT NULL,
    UnitID integer NOT NULL,
    VacancyStartDate date NOT NULL,
    VacancyEndDate date,
    LeaseID integer,
    VacancyCreatedEventID bigint NOT NULL,
    GeneratedCandidateCount integer NOT NULL DEFAULT 0,
    SelfScreenedCount integer NOT NULL DEFAULT 0,
    AppliedCount integer NOT NULL DEFAULT 0,
    RejectedCount integer NOT NULL DEFAULT 0,
    SelectedCount integer NOT NULL DEFAULT 0,
    TargetFillDate date
);
-- simulation.Vacancy.DaysVacant: computed on getdate() in T-SQL; OMITTED (documented divergence, no engine reader)

ALTER TABLE dbo.SchemaVersion ADD CONSTRAINT PK__SchemaVe__0F5401357CEDF900 PRIMARY KEY (Version);
ALTER TABLE reference.AcquisitionParameters ADD CONSTRAINT PK_AcquisitionParameters PRIMARY KEY (ParameterID);
ALTER TABLE reference.ComplianceParameters ADD CONSTRAINT PK__Complian__F80C629762B90E2F PRIMARY KEY (ParameterID);
ALTER TABLE reference.ComplianceParameters ADD CONSTRAINT UQ__Complian__67E409CA44EB41A2 UNIQUE (WorkType);
ALTER TABLE reference.EmployeeRole ADD CONSTRAINT PK_EmployeeRole PRIMARY KEY (RoleID);
ALTER TABLE reference.FirstName ADD CONSTRAINT PK_FirstName PRIMARY KEY (FirstNameID);
ALTER TABLE reference.FirstName ADD CONSTRAINT UQ_FirstName_Name UNIQUE (FirstName);
ALTER TABLE reference.LastName ADD CONSTRAINT PK_LastName PRIMARY KEY (LastNameID);
ALTER TABLE reference.LastName ADD CONSTRAINT UQ_LastName_Name UNIQUE (LastName);
ALTER TABLE reference.ParameterCategory ADD CONSTRAINT PK_ParameterCategory PRIMARY KEY (Category);
ALTER TABLE reference.ParameterRegistryDefault ADD CONSTRAINT PK_ParamDefault PRIMARY KEY (Category,Name);
ALTER TABLE reference.ParameterRegistryDefined ADD CONSTRAINT PK_ParamDefined PRIMARY KEY (ProjectionID,Category,Name);
ALTER TABLE reference.PersonSeed ADD CONSTRAINT PK_simPersonSeed PRIMARY KEY (SeedPersonID);
ALTER TABLE reference.PersonSeedRelationship ADD CONSTRAINT PK_simPersonSeedRelationship PRIMARY KEY (SeedPersonRelationshipID);
ALTER TABLE reference.Projection ADD CONSTRAINT PK_Projection PRIMARY KEY (ProjectionID);
ALTER TABLE reference.Projection ADD CONSTRAINT UQ_Projection_Name UNIQUE (Name);
ALTER TABLE reference.Properties ADD CONSTRAINT PK_Properties PRIMARY KEY (PropertyID);
ALTER TABLE reference.SeedFamily ADD CONSTRAINT PK_simSeedFamily PRIMARY KEY (SeedFamilyID);
ALTER TABLE reference.Tenants ADD CONSTRAINT PK_refTenants PRIMARY KEY (TenantRowID);
ALTER TABLE reference.TownParameterOverride ADD CONSTRAINT PK_TownParameterOverride PRIMARY KEY (Town,Category,Name);
ALTER TABLE reference.Units ADD CONSTRAINT PK_Units PRIMARY KEY (UnitID);
ALTER TABLE reference.Units ADD CONSTRAINT UQ_Unit_Property UNIQUE (PropertyID,UnitNumber);
ALTER TABLE simulation.ApplicantEvaluation ADD CONSTRAINT PK_simApplicantEvaluation PRIMARY KEY (RunID,EvaluationID);
ALTER TABLE simulation.ComplianceAttempt ADD CONSTRAINT PK_simComplianceAttempt PRIMARY KEY (RunID,AttemptID);
ALTER TABLE simulation.ComplianceStep ADD CONSTRAINT PK_simComplianceStep PRIMARY KEY (RunID,StepID);
ALTER TABLE simulation.ComplianceWorkItem ADD CONSTRAINT PK_simComplianceWorkItem PRIMARY KEY (RunID,WorkItemID);
ALTER TABLE simulation.Employees ADD CONSTRAINT PK_simEmployees PRIMARY KEY (RunID,EmployeeID);
ALTER TABLE simulation.Event ADD CONSTRAINT PK_simEvent PRIMARY KEY (RunID,EventID);
ALTER TABLE simulation.FundLedger ADD CONSTRAINT PK_simFundLedger PRIMARY KEY (RunID,EventID,LedgerDate);
ALTER TABLE simulation.GrantLedger ADD CONSTRAINT PK__GrantLed__5D6BC3D59A760B69 PRIMARY KEY (RunID,MonthIndex,GrantType);
ALTER TABLE simulation.Household ADD CONSTRAINT PK_simHousehold PRIMARY KEY (RunID,HouseholdID);
ALTER TABLE simulation.InflationSchedule ADD CONSTRAINT PK__Inflatio__8C6DA2B90B4EFA77 PRIMARY KEY (RunID,MonthIndex);
ALTER TABLE simulation.Lease ADD CONSTRAINT PK_simLease PRIMARY KEY (RunID,LeaseID);
ALTER TABLE simulation.LeaseDeposit ADD CONSTRAINT PK_simLeaseDeposit PRIMARY KEY (RunID,LeaseID);
ALTER TABLE simulation.LeaseDepositLedger ADD CONSTRAINT PK_simLeaseDepositLedger PRIMARY KEY (RunID,LedgerID);
ALTER TABLE simulation.LeaseTermination ADD CONSTRAINT PK_simLeaseTermination PRIMARY KEY (RunID,LeaseID);
ALTER TABLE simulation.LeaseTerminationLedger ADD CONSTRAINT PK_simLeaseTerminationLedger PRIMARY KEY (RunID,LedgerID);
ALTER TABLE simulation.MonthlyPaymentStatus ADD CONSTRAINT PK_simMonthlyPaymentStatus PRIMARY KEY (RunID,LeaseID,BillingMonth);
ALTER TABLE simulation.Payroll ADD CONSTRAINT PK_simPayroll PRIMARY KEY (RunID,PayrollID);
ALTER TABLE simulation.Person ADD CONSTRAINT PK_simPerson PRIMARY KEY (RunID,PersonID);
ALTER TABLE simulation.Properties ADD CONSTRAINT PK_simProperties PRIMARY KEY (RunID,PropertyID,EventID);
ALTER TABLE simulation.PropertyAcquisitionAttempt ADD CONSTRAINT PK_simPropertyAcquisitionAttempt PRIMARY KEY (RunID,AttemptID);
ALTER TABLE simulation.PropertyAcquisitionStep ADD CONSTRAINT PK_simPropertyAcquisitionStep PRIMARY KEY (RunID,AttemptID,StepID);
ALTER TABLE simulation.PropertyMarket ADD CONSTRAINT PK_simPropertyMarket PRIMARY KEY (RunID,PropertyMarketID);
ALTER TABLE simulation.PropertyUnits ADD CONSTRAINT PK_simPropertyUnits PRIMARY KEY (RunID,PropertyID,EventID,UnitID);
ALTER TABLE simulation.RentCollection ADD CONSTRAINT PK_simRentCollection PRIMARY KEY (RunID,CollectionID);
ALTER TABLE simulation.Run ADD CONSTRAINT PK_simRun PRIMARY KEY (RunID);
ALTER TABLE simulation.RunSnapshot ADD CONSTRAINT PK_simRunSnapshot PRIMARY KEY (RunID,SnapshotDate);
ALTER TABLE simulation.TenantCreditBalance ADD CONSTRAINT PK_simTenantCreditBalance PRIMARY KEY (RunID,HouseholdID);
ALTER TABLE simulation.TenantCreditLedger ADD CONSTRAINT PK_simTenantCreditLedger PRIMARY KEY (RunID,CreditTransactionID);
ALTER TABLE simulation.Tenants ADD CONSTRAINT PK_simTenants PRIMARY KEY (RunID,TenantID);
ALTER TABLE simulation.TurnoverWorkOrder ADD CONSTRAINT PK_simTurnoverWorkOrder PRIMARY KEY (RunID,TurnoverWorkOrderID);
ALTER TABLE simulation.Vacancy ADD CONSTRAINT PK_simVacancy PRIMARY KEY (RunID,VacancyID);

ALTER TABLE reference.PersonSeed ADD CONSTRAINT CK_PersonSeed_GenerationDepth CHECK (GenerationDepth>=(1) AND GenerationDepth<=(10));
ALTER TABLE reference.PersonSeedRelationship ADD CONSTRAINT CK_PSR_Dates CHECK (EndDate IS NULL OR StartDate IS NULL OR EndDate>=StartDate);
ALTER TABLE reference.PersonSeedRelationship ADD CONSTRAINT CK_PSR_NotSelf CHECK (SeedPersonID<>RelatedSeedPersonID);
ALTER TABLE reference.PersonSeedRelationship ADD CONSTRAINT CK_PSR_RelType CHECK (RelationshipType='CHILD' OR RelationshipType='PARENT' OR RelationshipType='SPOUSE');
ALTER TABLE reference.Projection ADD CONSTRAINT CK_Projection_Kind CHECK (Kind='scenario' OR Kind='stress' OR Kind='extension' OR Kind='baseline');
ALTER TABLE simulation.ApplicantEvaluation ADD CONSTRAINT CHK_ApplicantEvaluation_AdultCount CHECK (AdultCount>=(1));
ALTER TABLE simulation.ApplicantEvaluation ADD CONSTRAINT CHK_ApplicantEvaluation_ChildCount CHECK (ChildCount>=(0));
ALTER TABLE simulation.ApplicantEvaluation ADD CONSTRAINT CHK_ApplicantEvaluation_HouseholdType CHECK (HouseholdType='ROOMMATES' OR HouseholdType='FAMILY' OR HouseholdType='COUPLE' OR HouseholdType='SINGLE');
ALTER TABLE simulation.ApplicantEvaluation ADD CONSTRAINT CHK_ApplicantEvaluation_IncomeBand CHECK (HouseholdIncomeBand='B5' OR HouseholdIncomeBand='B4' OR HouseholdIncomeBand='B3' OR HouseholdIncomeBand='B2' OR HouseholdIncomeBand='B1');
ALTER TABLE simulation.ApplicantEvaluation ADD CONSTRAINT CHK_ApplicantEvaluation_Outcome CHECK (Outcome='REJECTED' OR Outcome='SELECTED');
ALTER TABLE simulation.ApplicantEvaluation ADD CONSTRAINT CHK_ApplicantEvaluation_Rejection CHECK (Outcome='SELECTED' AND RejectionReason IS NULL OR Outcome='REJECTED' AND RejectionReason IS NOT NULL);
ALTER TABLE simulation.ComplianceAttempt ADD CONSTRAINT CHK_ComplianceAttempt_BuildingScope CHECK (ScopeType='BUILDING' AND UnitID IS NULL OR ScopeType='UNIT' AND UnitID IS NOT NULL);
ALTER TABLE simulation.Household ADD CONSTRAINT CHK_Household_AdultCount CHECK (AdultCount>=(1));
ALTER TABLE simulation.Household ADD CONSTRAINT CHK_Household_ChildCount CHECK (ChildCount>=(0));
ALTER TABLE simulation.Household ADD CONSTRAINT CHK_Household_IncomeBand CHECK (HouseholdIncomeBand='B5' OR HouseholdIncomeBand='B4' OR HouseholdIncomeBand='B3' OR HouseholdIncomeBand='B2' OR HouseholdIncomeBand='B1');
ALTER TABLE simulation.Household ADD CONSTRAINT CHK_Household_TCSRedemptionProbability CHECK (TCSRedemptionProbability>=(0) AND TCSRedemptionProbability<=(1));
ALTER TABLE simulation.Household ADD CONSTRAINT CHK_Household_Type CHECK (HouseholdType='ROOMMATES' OR HouseholdType='FAMILY' OR HouseholdType='COUPLE' OR HouseholdType='SINGLE');
ALTER TABLE simulation.Lease ADD CONSTRAINT CHK_Lease_Dates CHECK (LeaseStartDate>=LeaseSignedDate);
ALTER TABLE simulation.Lease ADD CONSTRAINT CHK_Lease_EndDate CHECK (LeaseEndDate>LeaseStartDate);
ALTER TABLE simulation.Lease ADD CONSTRAINT CHK_Lease_MonthlyRent CHECK (MonthlyRent>(0));
ALTER TABLE simulation.Lease ADD CONSTRAINT CHK_Lease_RenewalDecision CHECK (RenewalDecision IS NULL OR (RenewalDecision='LANDLORD_NONRENEWAL' OR RenewalDecision='VOLUNTARY_EXIT' OR RenewalDecision='RENEW'));
ALTER TABLE simulation.Lease ADD CONSTRAINT CK_Lease_LeaseStatus CHECK (LeaseStatus='Terminated' OR LeaseStatus='Active');
ALTER TABLE simulation.LeaseDeposit ADD CONSTRAINT CHK_DepositAmounts CHECK (DepositRequiredAmount>=(0.00) AND DepositEscrowedAmount>=(0.00));
ALTER TABLE simulation.LeaseDeposit ADD CONSTRAINT CHK_DepositMethod CHECK (DepositMethod='INSTALLMENT' OR DepositMethod='FULL');
ALTER TABLE simulation.LeaseDeposit ADD CONSTRAINT CHK_DepositStatus CHECK (Status='APPLIED_TO_DAMAGES' OR Status='FORFEITED' OR Status='REFUNDED' OR Status='ACTIVE');
ALTER TABLE simulation.LeaseDeposit ADD CONSTRAINT CHK_InstallmentsPaidCount CHECK (InstallmentsPaidCount>=(0) AND InstallmentsPaidCount<=InstallmentsPlanned);
ALTER TABLE simulation.LeaseDeposit ADD CONSTRAINT CHK_simLeaseDeposit_SettlementOutcome CHECK (SettlementOutcome IS NULL OR (SettlementOutcome='PARTIAL_RETURN' OR SettlementOutcome='FULL_RETURN' OR SettlementOutcome='FORFEITURE'));
ALTER TABLE simulation.LeaseDeposit ADD CONSTRAINT CHK_simLeaseDeposit_SettlementStatus CHECK (SettlementStatus IS NULL OR (SettlementStatus='COMPLETED' OR SettlementStatus='PENDING'));
ALTER TABLE simulation.LeaseDepositLedger ADD CONSTRAINT CHK_BalanceAfter CHECK (BalanceAfter>=(0.00));
ALTER TABLE simulation.LeaseDepositLedger ADD CONSTRAINT CHK_DepositTxnType CHECK (TxnType='DAMAGE_WITHHOLD' OR TxnType='FORFEITURE' OR TxnType='REFUND' OR TxnType='INSTALLMENT_PAYMENT' OR TxnType='FULL_PAYMENT');
ALTER TABLE simulation.LeaseTermination ADD CONSTRAINT CHK_LeaseTermination_Type CHECK (TerminationType='NON_RENEWAL_TENANT' OR TerminationType='NON_RENEWAL_LANDLORD' OR TerminationType='EVICTION' OR TerminationType='VOLUNTARY');
ALTER TABLE simulation.LeaseTerminationLedger ADD CONSTRAINT CHK_LeaseTerminationLedger_TxnType CHECK (TxnType='VACANCY_CREATED' OR TxnType='TURNOVER_COMPLETE' OR TxnType='TURNOVER_START' OR TxnType='DAMAGE_WITHHOLD' OR TxnType='DEPOSIT_FORFEITURE' OR TxnType='DEPOSIT_REFUND' OR TxnType='DEPOSIT_SETTLEMENT' OR TxnType='LEASE_RENEWED' OR TxnType='NON_RENEWAL_TENANT' OR TxnType='NON_RENEWAL_LANDLORD' OR TxnType='ARREARS_WRITE_OFF' OR TxnType='EVICTION_COST' OR TxnType='EVICTION_EXECUTED' OR TxnType='EVICTION_FILED' OR TxnType='VOLUNTARY_NOTICE');
ALTER TABLE simulation.MonthlyPaymentStatus ADD CONSTRAINT CHK_MonthlyPaymentStatus_Status CHECK (PaymentStatus='REDEEMED' OR PaymentStatus='MISSED' OR PaymentStatus='LATE' OR PaymentStatus='ON_TIME');
ALTER TABLE simulation.PropertyAcquisitionAttempt ADD CONSTRAINT CHK_InspectionSeverity CHECK (InspectionSeverity='Major' OR InspectionSeverity='Moderate' OR InspectionSeverity='Minor' OR InspectionSeverity='Clean' OR InspectionSeverity IS NULL);
ALTER TABLE simulation.PropertyAcquisitionAttempt ADD CONSTRAINT CHK_LBResponseToCounter CHECK (LBResponseToCounter='Withdraw' OR LBResponseToCounter='AcceptCounter' OR LBResponseToCounter IS NULL);
ALTER TABLE simulation.PropertyAcquisitionAttempt ADD CONSTRAINT CHK_NegotiationOutcome CHECK (NegotiationOutcome='Withdrawal' OR NegotiationOutcome='NoConsessions' OR NegotiationOutcome='SellerRepairs' OR NegotiationOutcome='PriceReduction' OR NegotiationOutcome IS NULL);
ALTER TABLE simulation.PropertyAcquisitionAttempt ADD CONSTRAINT CHK_OfferStrategy CHECK (OfferStrategy='Premium' OR OfferStrategy='AtAsk' OR OfferStrategy='BelowAsk');
ALTER TABLE simulation.PropertyAcquisitionAttempt ADD CONSTRAINT CHK_PipelineStage CHECK (PipelineStage='Withdrawn' OR PipelineStage='PropertyUnavailable' OR PipelineStage='Timeout' OR PipelineStage='Failed' OR PipelineStage='Completed' OR PipelineStage='AwaitingClosing' OR PipelineStage='Negotiating' OR PipelineStage='AwaitingInspection' OR PipelineStage='SchedulingInspection' OR PipelineStage='AwaitingCounterResponse' OR PipelineStage='AwaitingSellerResponse' OR PipelineStage='MakingOffer');
ALTER TABLE simulation.PropertyAcquisitionAttempt ADD CONSTRAINT CHK_SellerResponse CHECK (SellerResponse='Rejected' OR SellerResponse='Countered' OR SellerResponse='Accepted' OR SellerResponse IS NULL);
ALTER TABLE simulation.PropertyMarket ADD CONSTRAINT CHK_PropertyMarket_Status CHECK (MarketStatus='LibertyBeeOwned' OR MarketStatus='OtherBuyerOwned' OR MarketStatus='LBOwned' OR MarketStatus='UnderContractLB' OR MarketStatus='Listed' OR MarketStatus='Available');
ALTER TABLE simulation.PropertyUnits ADD CONSTRAINT CHK_PropertyUnits_UnitStatus CHECK (UnitStatus='Compliance_In_Progress' OR UnitStatus='Under_Contract' OR UnitStatus='Pending_Move_Out' OR UnitStatus='Turnover' OR UnitStatus='Occupied' OR UnitStatus='Available');
ALTER TABLE simulation.RentCollection ADD CONSTRAINT CHK_RentCollection_Amount CHECK (PaymentStatus='REDEEMED' AND AmountCollected=(0) OR PaymentStatus<>'REDEEMED' AND AmountCollected>(0));
ALTER TABLE simulation.RentCollection ADD CONSTRAINT CHK_RentCollection_PaymentStatus CHECK (PaymentStatus='REDEEMED' OR PaymentStatus='MISSED' OR PaymentStatus='LATE' OR PaymentStatus='ON_TIME');
ALTER TABLE simulation.Run ADD CONSTRAINT CHK_Run_SnapshotCadence CHECK (SnapshotCadence IS NULL OR (SnapshotCadence='NONE' OR SnapshotCadence='HYBRID' OR SnapshotCadence='ANNUAL' OR SnapshotCadence='QUARTERLY' OR SnapshotCadence='MONTHLY'));
ALTER TABLE simulation.RunSnapshot ADD CONSTRAINT CHK_simRunSnapshot_MonthIndex CHECK (MonthIndex>=(1));
ALTER TABLE simulation.RunSnapshot ADD CONSTRAINT CHK_simRunSnapshot_OccupancyRate CHECK (OccupancyRate>=(0) AND OccupancyRate<=(1));
ALTER TABLE simulation.RunSnapshot ADD CONSTRAINT CHK_simRunSnapshot_SnapshotCadence CHECK (SnapshotCadence='HYBRID' OR SnapshotCadence='ANNUAL' OR SnapshotCadence='QUARTERLY' OR SnapshotCadence='MONTHLY');
ALTER TABLE simulation.RunSnapshot ADD CONSTRAINT CHK_simRunSnapshot_SnapshotSource CHECK (SnapshotSource='BACKFILL' OR SnapshotSource='LIVE');
ALTER TABLE simulation.RunSnapshot ADD CONSTRAINT CHK_simRunSnapshot_UnitsConsistent CHECK (((UnitsOccupied+UnitsVacant)+UnitsInTurnover)<=UnitsTotal);
ALTER TABLE simulation.RunSnapshot ADD CONSTRAINT CHK_simRunSnapshot_VacancyRate CHECK (VacancyRate>=(0) AND VacancyRate<=(1));
ALTER TABLE simulation.TenantCreditBalance ADD CONSTRAINT CHK_simTenantCreditBalance_AnnualRedemptionUsed CHECK (AnnualRedemptionUsed>=(0));
ALTER TABLE simulation.TenantCreditBalance ADD CONSTRAINT CHK_simTenantCreditBalance_CurrentBalance CHECK (CurrentBalance>=(0));
ALTER TABLE simulation.TenantCreditBalance ADD CONSTRAINT CHK_simTenantCreditBalance_LifetimeAccrued CHECK (LifetimeAccrued>=(0));
ALTER TABLE simulation.TenantCreditBalance ADD CONSTRAINT CHK_simTenantCreditBalance_LifetimeRedeemed CHECK (LifetimeRedeemed>=(0));
ALTER TABLE simulation.TenantCreditBalance ADD CONSTRAINT CHK_simTenantCreditBalance_Reconciliation CHECK (LifetimeAccrued>=(CurrentBalance+LifetimeRedeemed));
ALTER TABLE simulation.TenantCreditBalance ADD CONSTRAINT CHK_TCB_ExpiryStatus CHECK (ExpiryStatus='FORFEITED' OR ExpiryStatus='EXPIRED' OR ExpiryStatus='EXITED' OR ExpiryStatus='ACTIVE');
ALTER TABLE simulation.TenantCreditLedger ADD CONSTRAINT CHK_simTenantCreditLedger_AccrualAmount CHECK (TransactionType<>'ACCRUAL' OR Amount>(0));
ALTER TABLE simulation.TenantCreditLedger ADD CONSTRAINT CHK_simTenantCreditLedger_BalanceAfter CHECK (BalanceAfter>=(0));
ALTER TABLE simulation.TenantCreditLedger ADD CONSTRAINT CHK_simTenantCreditLedger_TransactionType CHECK (TransactionType='TRANSFER' OR TransactionType='FORFEITURE' OR TransactionType='REDEMPTION' OR TransactionType='ACCRUAL');
ALTER TABLE simulation.TurnoverWorkOrder ADD CONSTRAINT CHK_simTurnoverWorkOrder_DurationDays CHECK (DurationDays>=(0));
ALTER TABLE simulation.TurnoverWorkOrder ADD CONSTRAINT CHK_simTurnoverWorkOrder_Status CHECK (Status='SKIPPED' OR Status='COMPLETED' OR Status='IN_PROGRESS' OR Status='PENDING');
ALTER TABLE simulation.TurnoverWorkOrder ADD CONSTRAINT CHK_simTurnoverWorkOrder_TerminationType CHECK (TerminationType='LANDLORD_NONRENEWAL' OR TerminationType='EARLY_BREAK' OR TerminationType='VOLUNTARY' OR TerminationType='EVICTION');
ALTER TABLE simulation.TurnoverWorkOrder ADD CONSTRAINT CHK_simTurnoverWorkOrder_WorkItemType CHECK (WorkItemType='FINAL_INSPECTION' OR WorkItemType='RESTORATION' OR WorkItemType='PAINT' OR WorkItemType='CLEAN' OR WorkItemType='INSPECT');
ALTER TABLE simulation.TurnoverWorkOrder ADD CONSTRAINT CHK_simTurnoverWorkOrder_WorkSequence CHECK (WorkSequence>=(1) AND WorkSequence<=(5));
ALTER TABLE simulation.Vacancy ADD CONSTRAINT CHK_Vacancy_Dates CHECK (VacancyEndDate IS NULL OR VacancyEndDate>=VacancyStartDate);
ALTER TABLE simulation.Vacancy ADD CONSTRAINT CHK_Vacancy_Lease CHECK (VacancyEndDate IS NULL AND LeaseID IS NULL OR VacancyEndDate IS NOT NULL AND LeaseID IS NOT NULL);

ALTER TABLE reference.ParameterRegistryDefault ADD CONSTRAINT FK_ParamDefault_Category FOREIGN KEY (Category) REFERENCES reference.ParameterCategory (Category);
ALTER TABLE reference.ParameterRegistryDefined ADD CONSTRAINT FK_ParamDefined_Category FOREIGN KEY (Category) REFERENCES reference.ParameterCategory (Category);
ALTER TABLE reference.ParameterRegistryDefined ADD CONSTRAINT FK_ParamDefined_Projection FOREIGN KEY (ProjectionID) REFERENCES reference.Projection (ProjectionID) ON DELETE CASCADE;
ALTER TABLE reference.PersonSeed ADD CONSTRAINT FK_PersonSeed_SeedFamily FOREIGN KEY (SeedFamilyID) REFERENCES reference.SeedFamily (SeedFamilyID);
ALTER TABLE reference.PersonSeedRelationship ADD CONSTRAINT FK_PSR_Family FOREIGN KEY (SeedFamilyID) REFERENCES reference.SeedFamily (SeedFamilyID);
ALTER TABLE reference.PersonSeedRelationship ADD CONSTRAINT FK_PSR_Person FOREIGN KEY (SeedPersonID) REFERENCES reference.PersonSeed (SeedPersonID);
ALTER TABLE reference.PersonSeedRelationship ADD CONSTRAINT FK_PSR_Related FOREIGN KEY (RelatedSeedPersonID) REFERENCES reference.PersonSeed (SeedPersonID);
ALTER TABLE reference.TownParameterOverride ADD CONSTRAINT FK_TPO_Param FOREIGN KEY (Category,Name) REFERENCES reference.ParameterRegistryDefault (Category,Name);
ALTER TABLE reference.Units ADD CONSTRAINT FK_Units_Properties FOREIGN KEY (PropertyID) REFERENCES reference.Properties (PropertyID);
ALTER TABLE simulation.ApplicantEvaluation ADD CONSTRAINT FK_ApplicantEvaluation_Run FOREIGN KEY (RunID) REFERENCES simulation.Run (RunID);
ALTER TABLE simulation.ApplicantEvaluation ADD CONSTRAINT FK_ApplicantEvaluation_Vacancy FOREIGN KEY (RunID,VacancyID) REFERENCES simulation.Vacancy (RunID,VacancyID);
ALTER TABLE simulation.ComplianceAttempt ADD CONSTRAINT FK_ComplianceAttempt_Property FOREIGN KEY (PropertyID) REFERENCES reference.Properties (PropertyID);
ALTER TABLE simulation.ComplianceAttempt ADD CONSTRAINT FK_ComplianceAttempt_Run FOREIGN KEY (RunID) REFERENCES simulation.Run (RunID);
ALTER TABLE simulation.ComplianceAttempt ADD CONSTRAINT FK_ComplianceAttempt_Unit FOREIGN KEY (UnitID) REFERENCES reference.Units (UnitID);
ALTER TABLE simulation.ComplianceStep ADD CONSTRAINT FK_ComplianceStep_Attempt FOREIGN KEY (RunID,AttemptID) REFERENCES simulation.ComplianceAttempt (RunID,AttemptID);
ALTER TABLE simulation.ComplianceStep ADD CONSTRAINT FK_ComplianceStep_Event FOREIGN KEY (RunID,EventID) REFERENCES simulation.Event (RunID,EventID);
ALTER TABLE simulation.ComplianceStep ADD CONSTRAINT FK_ComplianceStep_WorkItem FOREIGN KEY (RunID,WorkItemID) REFERENCES simulation.ComplianceWorkItem (RunID,WorkItemID);
ALTER TABLE simulation.ComplianceWorkItem ADD CONSTRAINT FK_ComplianceWorkItem_Attempt FOREIGN KEY (RunID,AttemptID) REFERENCES simulation.ComplianceAttempt (RunID,AttemptID);
ALTER TABLE simulation.ComplianceWorkItem ADD CONSTRAINT FK_ComplianceWorkItem_Parent FOREIGN KEY (RunID,ParentWorkItemID) REFERENCES simulation.ComplianceWorkItem (RunID,WorkItemID);
ALTER TABLE simulation.Employees ADD CONSTRAINT FK_Employees_Role FOREIGN KEY (RoleID) REFERENCES reference.EmployeeRole (RoleID);
ALTER TABLE simulation.Employees ADD CONSTRAINT FK_Employees_Run FOREIGN KEY (RunID) REFERENCES simulation.Run (RunID);
ALTER TABLE simulation.Event ADD CONSTRAINT FK_Event_Run FOREIGN KEY (RunID) REFERENCES simulation.Run (RunID);
ALTER TABLE simulation.FundLedger ADD CONSTRAINT FK_FundLedger_Run FOREIGN KEY (RunID) REFERENCES simulation.Run (RunID);
ALTER TABLE simulation.GrantLedger ADD CONSTRAINT FK_GrantLedger_Event FOREIGN KEY (RunID,EventID) REFERENCES simulation.Event (RunID,EventID);
ALTER TABLE simulation.Household ADD CONSTRAINT FK_Household_CreatedEvent FOREIGN KEY (RunID,CreatedEventID) REFERENCES simulation.Event (RunID,EventID);
ALTER TABLE simulation.Household ADD CONSTRAINT FK_Household_Run FOREIGN KEY (RunID) REFERENCES simulation.Run (RunID);
ALTER TABLE simulation.InflationSchedule ADD CONSTRAINT FK_InflationSchedule_Run FOREIGN KEY (RunID) REFERENCES simulation.Run (RunID);
ALTER TABLE simulation.Lease ADD CONSTRAINT FK_Lease_Household FOREIGN KEY (RunID,HouseholdID) REFERENCES simulation.Household (RunID,HouseholdID);
ALTER TABLE simulation.Lease ADD CONSTRAINT FK_Lease_Run FOREIGN KEY (RunID) REFERENCES simulation.Run (RunID);
ALTER TABLE simulation.Lease ADD CONSTRAINT FK_Lease_SignedEvent FOREIGN KEY (RunID,SignedEventID) REFERENCES simulation.Event (RunID,EventID);
ALTER TABLE simulation.Lease ADD CONSTRAINT FK_Lease_Vacancy FOREIGN KEY (RunID,VacancyID) REFERENCES simulation.Vacancy (RunID,VacancyID);
ALTER TABLE simulation.LeaseDeposit ADD CONSTRAINT FK_LeaseDeposit_Lease FOREIGN KEY (RunID,LeaseID) REFERENCES simulation.Lease (RunID,LeaseID);
ALTER TABLE simulation.LeaseDeposit ADD CONSTRAINT FK_LeaseDeposit_Run FOREIGN KEY (RunID) REFERENCES simulation.Run (RunID);
ALTER TABLE simulation.LeaseDepositLedger ADD CONSTRAINT FK_LeaseDepositLedger_Event FOREIGN KEY (RunID,EventID) REFERENCES simulation.Event (RunID,EventID);
ALTER TABLE simulation.LeaseDepositLedger ADD CONSTRAINT FK_LeaseDepositLedger_Lease FOREIGN KEY (RunID,LeaseID) REFERENCES simulation.Lease (RunID,LeaseID);
ALTER TABLE simulation.LeaseDepositLedger ADD CONSTRAINT FK_LeaseDepositLedger_Run FOREIGN KEY (RunID) REFERENCES simulation.Run (RunID);
ALTER TABLE simulation.LeaseTermination ADD CONSTRAINT FK_LeaseTermination_Lease FOREIGN KEY (RunID,LeaseID) REFERENCES simulation.Lease (RunID,LeaseID);
ALTER TABLE simulation.LeaseTermination ADD CONSTRAINT FK_LeaseTermination_Run FOREIGN KEY (RunID) REFERENCES simulation.Run (RunID);
ALTER TABLE simulation.LeaseTerminationLedger ADD CONSTRAINT FK_LeaseTerminationLedger_Event FOREIGN KEY (RunID,EventID) REFERENCES simulation.Event (RunID,EventID);
ALTER TABLE simulation.LeaseTerminationLedger ADD CONSTRAINT FK_LeaseTerminationLedger_Lease FOREIGN KEY (RunID,LeaseID) REFERENCES simulation.Lease (RunID,LeaseID);
ALTER TABLE simulation.LeaseTerminationLedger ADD CONSTRAINT FK_LeaseTerminationLedger_Run FOREIGN KEY (RunID) REFERENCES simulation.Run (RunID);
ALTER TABLE simulation.MonthlyPaymentStatus ADD CONSTRAINT FK_MonthlyPaymentStatus_Lease FOREIGN KEY (RunID,LeaseID) REFERENCES simulation.Lease (RunID,LeaseID);
ALTER TABLE simulation.MonthlyPaymentStatus ADD CONSTRAINT FK_MonthlyPaymentStatus_Run FOREIGN KEY (RunID) REFERENCES simulation.Run (RunID);
ALTER TABLE simulation.Payroll ADD CONSTRAINT FK_Payroll_Employee FOREIGN KEY (RunID,EmployeeID) REFERENCES simulation.Employees (RunID,EmployeeID);
ALTER TABLE simulation.Payroll ADD CONSTRAINT FK_Payroll_Run FOREIGN KEY (RunID) REFERENCES simulation.Run (RunID);
ALTER TABLE simulation.Person ADD CONSTRAINT FK_Person_CreatedEvent FOREIGN KEY (RunID,CreatedEventID) REFERENCES simulation.Event (RunID,EventID);
ALTER TABLE simulation.Person ADD CONSTRAINT FK_Person_Household FOREIGN KEY (RunID,HouseholdID) REFERENCES simulation.Household (RunID,HouseholdID);
ALTER TABLE simulation.Person ADD CONSTRAINT FK_Person_Run FOREIGN KEY (RunID) REFERENCES simulation.Run (RunID);
ALTER TABLE simulation.PropertyAcquisitionAttempt ADD CONSTRAINT FK_PropertyAcquisitionAttempt_Property FOREIGN KEY (PropertyID) REFERENCES reference.Properties (PropertyID);
ALTER TABLE simulation.PropertyAcquisitionAttempt ADD CONSTRAINT FK_PropertyAcquisitionAttempt_Run FOREIGN KEY (RunID) REFERENCES simulation.Run (RunID);
ALTER TABLE simulation.PropertyAcquisitionStep ADD CONSTRAINT FK_PropertyAcquisitionStep_Attempt FOREIGN KEY (RunID,AttemptID) REFERENCES simulation.PropertyAcquisitionAttempt (RunID,AttemptID);
ALTER TABLE simulation.PropertyAcquisitionStep ADD CONSTRAINT FK_PropertyAcquisitionStep_Event FOREIGN KEY (RunID,EventID) REFERENCES simulation.Event (RunID,EventID);
ALTER TABLE simulation.PropertyMarket ADD CONSTRAINT FK_PropertyMarket_Property FOREIGN KEY (PropertyID) REFERENCES reference.Properties (PropertyID);
ALTER TABLE simulation.PropertyMarket ADD CONSTRAINT FK_PropertyMarket_Run FOREIGN KEY (RunID) REFERENCES simulation.Run (RunID);
ALTER TABLE simulation.PropertyUnits ADD CONSTRAINT FK_PropertyUnits_Properties FOREIGN KEY (RunID,PropertyID,EventID) REFERENCES simulation.Properties (RunID,PropertyID,EventID);
ALTER TABLE simulation.RentCollection ADD CONSTRAINT FK_RentCollection_Event FOREIGN KEY (RunID,CreatedEventID) REFERENCES simulation.Event (RunID,EventID);
ALTER TABLE simulation.RentCollection ADD CONSTRAINT FK_RentCollection_Lease FOREIGN KEY (RunID,LeaseID) REFERENCES simulation.Lease (RunID,LeaseID);
ALTER TABLE simulation.RentCollection ADD CONSTRAINT FK_RentCollection_Run FOREIGN KEY (RunID) REFERENCES simulation.Run (RunID);
ALTER TABLE simulation.RunSnapshot ADD CONSTRAINT FK_simRunSnapshot_Run FOREIGN KEY (RunID) REFERENCES simulation.Run (RunID);
ALTER TABLE simulation.TenantCreditBalance ADD CONSTRAINT FK_simTenantCreditBalance_Event FOREIGN KEY (RunID,LastUpdatedEventID) REFERENCES simulation.Event (RunID,EventID);
ALTER TABLE simulation.TenantCreditBalance ADD CONSTRAINT FK_simTenantCreditBalance_Household FOREIGN KEY (RunID,HouseholdID) REFERENCES simulation.Household (RunID,HouseholdID);
ALTER TABLE simulation.TenantCreditBalance ADD CONSTRAINT FK_simTenantCreditBalance_Run FOREIGN KEY (RunID) REFERENCES simulation.Run (RunID);
ALTER TABLE simulation.TenantCreditLedger ADD CONSTRAINT FK_simTenantCreditLedger_Collection FOREIGN KEY (RunID,RelatedCollectionID) REFERENCES simulation.RentCollection (RunID,CollectionID);
ALTER TABLE simulation.TenantCreditLedger ADD CONSTRAINT FK_simTenantCreditLedger_Event FOREIGN KEY (RunID,CreatedEventID) REFERENCES simulation.Event (RunID,EventID);
ALTER TABLE simulation.TenantCreditLedger ADD CONSTRAINT FK_simTenantCreditLedger_Household FOREIGN KEY (RunID,HouseholdID) REFERENCES simulation.Household (RunID,HouseholdID);
ALTER TABLE simulation.TenantCreditLedger ADD CONSTRAINT FK_simTenantCreditLedger_Lease FOREIGN KEY (RunID,RelatedLeaseID) REFERENCES simulation.Lease (RunID,LeaseID);
ALTER TABLE simulation.TenantCreditLedger ADD CONSTRAINT FK_simTenantCreditLedger_Run FOREIGN KEY (RunID) REFERENCES simulation.Run (RunID);
ALTER TABLE simulation.TurnoverWorkOrder ADD CONSTRAINT FK_simTurnoverWorkOrder_simEvent FOREIGN KEY (RunID,EventID) REFERENCES simulation.Event (RunID,EventID);
ALTER TABLE simulation.TurnoverWorkOrder ADD CONSTRAINT FK_simTurnoverWorkOrder_simLease FOREIGN KEY (RunID,LeaseID) REFERENCES simulation.Lease (RunID,LeaseID);
ALTER TABLE simulation.TurnoverWorkOrder ADD CONSTRAINT FK_simTurnoverWorkOrder_simRun FOREIGN KEY (RunID) REFERENCES simulation.Run (RunID);
ALTER TABLE simulation.Vacancy ADD CONSTRAINT FK_Vacancy_CreatedEvent FOREIGN KEY (RunID,VacancyCreatedEventID) REFERENCES simulation.Event (RunID,EventID);
ALTER TABLE simulation.Vacancy ADD CONSTRAINT FK_Vacancy_Run FOREIGN KEY (RunID) REFERENCES simulation.Run (RunID);

CREATE INDEX IX_ParamDefined_Projection ON reference.ParameterRegistryDefined (ProjectionID);
CREATE INDEX IX_PersonSeed_BirthDate ON reference.PersonSeed (BirthDate);
CREATE INDEX IX_PersonSeed_FamilyDepth ON reference.PersonSeed (SeedFamilyID, GenerationDepth);
CREATE INDEX IX_PersonSeed_Name ON reference.PersonSeed (LastName, FirstName);
CREATE INDEX IX_PSR_Family ON reference.PersonSeedRelationship (SeedFamilyID);
CREATE INDEX IX_PSR_Person ON reference.PersonSeedRelationship (SeedPersonID);
CREATE UNIQUE INDEX UX_PSR_UniqueEdge ON reference.PersonSeedRelationship (SeedPersonID, RelatedSeedPersonID, RelationshipType);
CREATE INDEX IX_Projection_Kind ON reference.Projection (Kind);
CREATE INDEX IX_Projection_ScenarioTag ON reference.Projection (ScenarioTag);
CREATE INDEX IX_SeedFamily_GenerationDepthMax ON reference.SeedFamily (GenerationDepthMax);
CREATE INDEX IX_ApplicantEvaluation_Date ON simulation.ApplicantEvaluation (RunID, EvaluatedDate);
CREATE INDEX IX_ApplicantEvaluation_Outcome ON simulation.ApplicantEvaluation (RunID, Outcome);
CREATE INDEX IX_ApplicantEvaluation_Vacancy ON simulation.ApplicantEvaluation (RunID, VacancyID);
CREATE INDEX IX_ComplianceAttempt_RunProperty_Active ON simulation.ComplianceAttempt (RunID, PropertyID, IsActive) INCLUDE (ScopeType, TriggerType, StartDate, NextActionDate);
CREATE INDEX IX_ComplianceWorkItem_RunProperty_Status ON simulation.ComplianceWorkItem (RunID, PropertyID, UnitID, Status) INCLUDE (WorkType, WorkItemID, ParentWorkItemID, Severity);
CREATE INDEX IX_ComplianceWorkItem_Run_Status_Scheduled ON simulation.ComplianceWorkItem (RunID, Status, ScheduledDate) INCLUDE (PropertyID, UnitID, WorkType, AttemptID, DurationDays, StartDate);
CREATE INDEX IX_FundLedger_RunDateEvent_Cover ON simulation.FundLedger (RunID, LedgerDate, EventID) INCLUDE (CashBalance, CSFBalance, EIPBalance, EscrowBalance, CashHoldBalance);
CREATE INDEX IX_Household_CreatedDate ON simulation.Household (RunID, CreatedDate);
CREATE INDEX IX_Lease_Household ON simulation.Lease (RunID, HouseholdID);
CREATE INDEX IX_Lease_SignedDate ON simulation.Lease (RunID, LeaseSignedDate);
CREATE INDEX IX_Lease_Status ON simulation.Lease (RunID, LeaseStatus);
CREATE INDEX IX_Lease_Unit ON simulation.Lease (RunID, UnitID);
CREATE INDEX IX_Lease_Vacancy ON simulation.Lease (RunID, VacancyID);
CREATE INDEX IX_LeaseDeposit_FundingStatus ON simulation.LeaseDeposit (RunID, DepositFundedDate) INCLUDE (LeaseID, DepositRequiredAmount, DepositEscrowedAmount);
CREATE INDEX IX_LeaseDeposit_Status ON simulation.LeaseDeposit (RunID, Status) INCLUDE (DepositRequiredAmount, DepositEscrowedAmount);
CREATE INDEX IX_LeaseDepositLedger_Event ON simulation.LeaseDepositLedger (RunID, EventID);
CREATE INDEX IX_LeaseDepositLedger_Lease ON simulation.LeaseDepositLedger (RunID, LeaseID, TxnDate, LedgerID);
CREATE INDEX IX_LeaseDepositLedger_TxnType ON simulation.LeaseDepositLedger (RunID, TxnType) INCLUDE (Amount, TxnDate);
CREATE INDEX IX_LeaseTermination_Date ON simulation.LeaseTermination (RunID, TerminationDate);
CREATE INDEX IX_LeaseTermination_Type ON simulation.LeaseTermination (RunID, TerminationType);
CREATE INDEX IX_LeaseTerminationLedger_Date ON simulation.LeaseTerminationLedger (RunID, TxnDate);
CREATE INDEX IX_LeaseTerminationLedger_Lease ON simulation.LeaseTerminationLedger (RunID, LeaseID);
CREATE INDEX IX_LeaseTerminationLedger_Type ON simulation.LeaseTerminationLedger (RunID, TxnType);
CREATE INDEX IX_MonthlyPaymentStatus_Date ON simulation.MonthlyPaymentStatus (RunID, BillingMonth);
CREATE INDEX IX_MonthlyPaymentStatus_Unpaid ON simulation.MonthlyPaymentStatus (RunID, BillingMonth);
CREATE INDEX IX_Person_CreatedDate ON simulation.Person (RunID, CreatedDate);
CREATE INDEX IX_Person_Household ON simulation.Person (RunID, HouseholdID);
CREATE INDEX IX_PropertyAcquisitionStep_Attempt ON simulation.PropertyAcquisitionStep (RunID, AttemptID) INCLUDE (EffectiveDate, StepType);
CREATE INDEX IX_PropertyAcquisitionStep_Date ON simulation.PropertyAcquisitionStep (RunID, EffectiveDate) INCLUDE (AttemptID, StepType);
CREATE INDEX IX_PropertyAcquisitionStep_Event ON simulation.PropertyAcquisitionStep (RunID, EventID);
CREATE INDEX IX_PropertyMarket_StatusSweep ON simulation.PropertyMarket (RunID, MarketStatus, ExpirationDate) INCLUDE (PropertyID, ExpectedReturnDate, CurrentListingPrice);
CREATE INDEX IX_PropertyUnits_UnitStatus ON simulation.PropertyUnits (RunID, UnitStatus);
CREATE INDEX IX_RentCollection_PaymentStatus ON simulation.RentCollection (RunID, LeaseID, PaymentStatus);
CREATE INDEX IX_simRunSnapshot_RunMonth ON simulation.RunSnapshot (RunID, MonthIndex);
CREATE INDEX IX_TenantCreditBalance_ExpirySweep ON simulation.TenantCreditBalance (RunID, CreditExpiryDate) INCLUDE (HouseholdID, CurrentBalance);
CREATE INDEX IX_simTenantCreditLedger_HouseholdDate ON simulation.TenantCreditLedger (RunID, HouseholdID, TransactionDate);
CREATE INDEX IX_simTurnoverWorkOrder_DailyProcessor ON simulation.TurnoverWorkOrder (RunID, Status, ScheduledEndDate, ScheduledStartDate);
CREATE INDEX IX_simTurnoverWorkOrder_RunLeaseUnit ON simulation.TurnoverWorkOrder (RunID, LeaseID, UnitID) INCLUDE (WorkSequence, Status, ScheduledStartDate, ScheduledEndDate);
CREATE INDEX IX_Vacancy_StartDate ON simulation.Vacancy (RunID, VacancyStartDate);
CREATE INDEX IX_Vacancy_Status ON simulation.Vacancy (RunID, VacancyEndDate);
CREATE INDEX IX_Vacancy_Unit ON simulation.Vacancy (RunID, UnitID);