"""PG schema cut — generate the PostgreSQL baseline from the live SQL Server catalog.

The cut_silver precedent applied to the engine port (pg_port_design.md, approved
2026-08-14): rather than porting 78 historical T-SQL migrations, the PG schema of
record is generated from a migrated SQL Server DB (through the current chain) and
becomes the `libertybee_gold` TEMPLATE database — `CREATE DATABASE ... TEMPLATE
libertybee_gold` IS the Gold restore on PG.

Scope: schemas dbo / reference / simulation (the engine's surface). farm.* and
v1.* ride their own lanes (farm store migration; corpus re-sweep).

FAIL-LOUD: any unmapped type, untranslatable default/CHECK, or unexpected
computed column raises with the object named. Known documented divergence:
simulation.Vacancy.DaysVacant (non-persisted computed column on getdate(),
read by NO engine code) is OMITTED — PG generated columns must be immutable.

Usage:
  python environmentscripts/pg_schema_cut.py --env <sqlserver_env> --out pg_schema.sql
  python environmentscripts/pg_schema_cut.py --env <sqlserver_env> --build-gold
"""
import argparse
import os
import re
import sys

sys.path.insert(0, os.path.join(os.path.dirname(__file__), "..", "app", "src"))

from database_manager import DatabaseManager  # noqa: E402

SCHEMAS = ("dbo", "reference", "simulation")
GOLD_DB = "libertybee_gold"

KNOWN_COMPUTED_OMISSIONS = {("simulation", "Vacancy", "DaysVacant")}

TYPE_MAP = {
    "int": "integer", "bigint": "bigint", "smallint": "smallint",
    "tinyint": "smallint", "float": "double precision",
    "real": "real", "date": "date", "datetime": "timestamp",
    "datetime2": "timestamp", "time": "time", "money": "numeric(19,4)",
    # bit -> smallint, NOT boolean: engine SQL compares bit columns to
    # integer literals (WHERE IsActive = 1) and binds int params — PG
    # booleans reject both. 0/1 value semantics preserved end to end;
    # the DB-level 0/1 domain guarantee weakens (documented divergence,
    # revisit at the re-sweep).
    "bit": "smallint",
}


def map_type(type_name, max_length, precision, scale, tbl, col):
    t = type_name.lower()
    if t in TYPE_MAP:
        return TYPE_MAP[t]
    if t in ("decimal", "numeric"):
        return f"numeric({precision},{scale})"
    if t in ("varchar", "char", "nvarchar", "nchar"):
        # citext, NOT varchar: the engine's string comparisons rely on SQL
        # Server's CASE-INSENSITIVE default collation (found live: leases are
        # WRITTEN with LeaseStatus 'ACTIVE' and QUERIED as 'Active').
        # citext mirrors those semantics exactly and keeps LIKE working.
        # Documented weakenings vs T-SQL: no length enforcement, no binary-
        # case identity — both revisit at the re-sweep; the casing hygiene
        # itself is a filed KD.
        return "citext"
    if t in ("varbinary", "binary"):
        return "bytea"
    if t == "uniqueidentifier":
        return "uuid"
    raise ValueError(f"unmapped SQL Server type '{type_name}' at {tbl}.{col}")


def translate_expr(expr, context):
    """T-SQL constraint/default expression -> PG. Brackets stripped, N'' ->
    '', known functions mapped. Fail-loud on leftovers."""
    out = expr
    out = re.sub(r"\[([^\]]+)\]", r"\1", out)
    out = re.sub(r"\bN'", "'", out)
    out = re.sub(r"(?i)\bgetdate\(\)", "CURRENT_TIMESTAMP", out)
    out = re.sub(r"(?i)\bsysutcdatetime\(\)", "CURRENT_TIMESTAMP", out)
    out = re.sub(r"(?i)\bsuser_sname\(\)", "CURRENT_USER", out)
    if "[" in out or "]" in out:
        raise ValueError(f"bracket survived translation in {context}: {expr}")
    lowered = out.lower()
    for banned in ("newid(", "datediff(", "dateadd(", "convert(", "isnull("):
        if banned in lowered:
            raise ValueError(f"untranslated function {banned} in {context}: {expr}")
    return out


def generate(db):
    ddl = ["-- Generated by pg_schema_cut.py — the PG baseline of record",
           "-- Source: the SQL Server catalog through the current migration chain",
           "CREATE EXTENSION IF NOT EXISTS citext;",
           "",
           "-- T-SQL date-function compatibility shims: the regression suite (and",
           "-- adopter SQL) uses YEAR()/MONTH()/DATEFROMPARTS()/EOMONTH(), which PG",
           "-- lacks. PG happily hosts functions with these names — four IMMUTABLE",
           "-- one-liners erase the whole dialect class. date-typed args only (the",
           "-- engine's date columns); T-SQL semantics preserved exactly.",
           "CREATE OR REPLACE FUNCTION year(d date) RETURNS int",
           "    LANGUAGE sql IMMUTABLE AS 'SELECT EXTRACT(YEAR FROM d)::int';",
           "CREATE OR REPLACE FUNCTION month(d date) RETURNS int",
           "    LANGUAGE sql IMMUTABLE AS 'SELECT EXTRACT(MONTH FROM d)::int';",
           "CREATE OR REPLACE FUNCTION day(d date) RETURNS int",
           "    LANGUAGE sql IMMUTABLE AS 'SELECT EXTRACT(DAY FROM d)::int';",
           "CREATE OR REPLACE FUNCTION datefromparts(y int, m int, dd int) RETURNS date",
           "    LANGUAGE sql IMMUTABLE AS 'SELECT make_date(y, m, dd)';",
           "CREATE OR REPLACE FUNCTION eomonth(d date) RETURNS date",
           "    LANGUAGE sql IMMUTABLE AS",
           "    $$SELECT (date_trunc('month', d) + INTERVAL '1 month' - INTERVAL '1 day')::date$$;",
           ""]
    for s in SCHEMAS:
        if s != "dbo":
            ddl.append(f"CREATE SCHEMA IF NOT EXISTS {s};")
    ddl.append("CREATE SCHEMA IF NOT EXISTS dbo;")
    ddl.append("")

    tables = db.execute_query(
        "SELECT s.name, t.name, t.object_id FROM sys.tables t "
        "JOIN sys.schemas s ON s.schema_id = t.schema_id "
        "WHERE s.name IN ('dbo','reference','simulation') ORDER BY s.name, t.name")

    identity_cols = []  # (schema, table, column) for setval after data port

    for schema, table, object_id in tables:
        cols_rows = db.execute_query(
            "SELECT c.name, ty.name, c.max_length, c.precision, c.scale, "
            "c.is_nullable, c.is_identity, c.is_computed, dc.definition "
            "FROM sys.columns c "
            "JOIN sys.types ty ON ty.user_type_id = c.user_type_id "
            "LEFT JOIN sys.default_constraints dc ON dc.parent_object_id = c.object_id "
            "  AND dc.parent_column_id = c.column_id "
            "WHERE c.object_id = ? ORDER BY c.column_id", (object_id,))
        col_lines = []
        omission_notes = []
        for (col, ty, maxlen, prec, scale, nullable, is_identity,
             is_computed, default_def) in cols_rows:
            if is_computed:
                if (schema, table, col) in KNOWN_COMPUTED_OMISSIONS:
                    omission_notes.append(
                        f"-- {schema}.{table}.{col}: computed on getdate() in "
                        f"T-SQL; OMITTED (documented divergence, no engine reader)")
                    continue
                raise ValueError(f"unexpected computed column {schema}.{table}.{col}")
            pg_type = map_type(ty, maxlen, prec, scale, f"{schema}.{table}", col)
            line = f"    {col} {pg_type}"
            if is_identity:
                line += " GENERATED BY DEFAULT AS IDENTITY"
                identity_cols.append((schema, table, col))
            if not nullable:
                line += " NOT NULL"
            if default_def is not None and not is_identity:
                d = translate_expr(default_def, f"default on {schema}.{table}.{col}")
                d = d.strip()
                while d.startswith("(") and d.endswith(")"):
                    d = d[1:-1]
                if pg_type == "boolean":
                    if d not in ("0", "1"):
                        raise ValueError(
                            f"non-0/1 default on boolean {schema}.{table}.{col}: {d}")
                    d = "true" if d == "1" else "false"
                line += f" DEFAULT {d}"
            col_lines.append(line)
        ddl.append(f"CREATE TABLE {schema}.{table} (")
        ddl.append(",\n".join(col_lines))
        ddl.append(");")
        ddl.extend(omission_notes)
        ddl.append("")

    # PK + unique constraints
    kc = db.execute_query(
        "SELECT s.name, t.name, kc.name, kc.type, "
        "  STRING_AGG(c.name, ',') WITHIN GROUP (ORDER BY ic.key_ordinal) "
        "FROM sys.key_constraints kc "
        "JOIN sys.tables t ON t.object_id = kc.parent_object_id "
        "JOIN sys.schemas s ON s.schema_id = t.schema_id "
        "JOIN sys.index_columns ic ON ic.object_id = kc.parent_object_id "
        "  AND ic.index_id = kc.unique_index_id "
        "JOIN sys.columns c ON c.object_id = ic.object_id AND c.column_id = ic.column_id "
        "WHERE s.name IN ('dbo','reference','simulation') "
        "GROUP BY s.name, t.name, kc.name, kc.type ORDER BY s.name, t.name, kc.name")
    for schema, table, cname, ctype, cols in kc:
        kind = "PRIMARY KEY" if ctype.strip() == "PK" else "UNIQUE"
        ddl.append(f"ALTER TABLE {schema}.{table} ADD CONSTRAINT {cname} {kind} ({cols});")
    ddl.append("")

    # CHECK constraints
    checks = db.execute_query(
        "SELECT s.name, t.name, cc.name, cc.definition FROM sys.check_constraints cc "
        "JOIN sys.tables t ON t.object_id = cc.parent_object_id "
        "JOIN sys.schemas s ON s.schema_id = t.schema_id "
        "WHERE s.name IN ('dbo','reference','simulation') ORDER BY s.name, t.name, cc.name")
    for schema, table, cname, definition in checks:
        expr = translate_expr(definition, f"CHECK {cname} on {schema}.{table}")
        ddl.append(f"ALTER TABLE {schema}.{table} ADD CONSTRAINT {cname} CHECK {expr};")
    ddl.append("")

    # FKs (after all tables exist)
    fks = db.execute_query(
        "SELECT s.name, t.name, fk.name, "
        "  STRING_AGG(pc.name, ',') WITHIN GROUP (ORDER BY fkc.constraint_column_id), "
        "  rs.name, rt.name, "
        "  STRING_AGG(rc.name, ',') WITHIN GROUP (ORDER BY fkc.constraint_column_id), "
        "  fk.delete_referential_action_desc, fk.update_referential_action_desc "
        "FROM sys.foreign_keys fk "
        "JOIN sys.tables t ON t.object_id = fk.parent_object_id "
        "JOIN sys.schemas s ON s.schema_id = t.schema_id "
        "JOIN sys.tables rt ON rt.object_id = fk.referenced_object_id "
        "JOIN sys.schemas rs ON rs.schema_id = rt.schema_id "
        "JOIN sys.foreign_key_columns fkc ON fkc.constraint_object_id = fk.object_id "
        "JOIN sys.columns pc ON pc.object_id = fkc.parent_object_id "
        "  AND pc.column_id = fkc.parent_column_id "
        "JOIN sys.columns rc ON rc.object_id = fkc.referenced_object_id "
        "  AND rc.column_id = fkc.referenced_column_id "
        "WHERE s.name IN ('dbo','reference','simulation') "
        "GROUP BY s.name, t.name, fk.name, rs.name, rt.name, "
        "  fk.delete_referential_action_desc, fk.update_referential_action_desc "
        "ORDER BY s.name, t.name, fk.name")
    for (schema, table, fname, cols, rschema, rtable, rcols,
         del_action, upd_action) in fks:
        stmt = (f"ALTER TABLE {schema}.{table} ADD CONSTRAINT {fname} "
                f"FOREIGN KEY ({cols}) REFERENCES {rschema}.{rtable} ({rcols})")
        if del_action != "NO_ACTION":
            stmt += f" ON DELETE {del_action.replace('_', ' ')}"
        if upd_action != "NO_ACTION":
            stmt += f" ON UPDATE {upd_action.replace('_', ' ')}"
        ddl.append(stmt + ";")
    ddl.append("")

    # non-constraint indexes (aggregate in Python — T-SQL disallows two
    # ordered STRING_AGGs in one scope)
    idx_rows = db.execute_query(
        "SELECT s.name, t.name, i.name, i.is_unique, ic.is_included_column, "
        "  c.name, ic.key_ordinal, ic.index_column_id "
        "FROM sys.indexes i "
        "JOIN sys.tables t ON t.object_id = i.object_id "
        "JOIN sys.schemas s ON s.schema_id = t.schema_id "
        "JOIN sys.index_columns ic ON ic.object_id = i.object_id AND ic.index_id = i.index_id "
        "JOIN sys.columns c ON c.object_id = ic.object_id AND c.column_id = ic.column_id "
        "WHERE s.name IN ('dbo','reference','simulation') "
        "  AND i.is_primary_key = 0 AND i.is_unique_constraint = 0 AND i.type > 0 "
        "ORDER BY s.name, t.name, i.name, ic.is_included_column, "
        "  ic.key_ordinal, ic.index_column_id")
    indexes = {}
    for schema, table, iname, is_unique, is_incl, col, _ko, _ic in idx_rows:
        entry = indexes.setdefault((schema, table, iname), [bool(is_unique), [], []])
        entry[2 if is_incl else 1].append(col)
    for (schema, table, iname), (is_unique, keys, includes) in sorted(indexes.items()):
        u = "UNIQUE " if is_unique else ""
        inc = f" INCLUDE ({', '.join(includes)})" if includes else ""
        ddl.append(f"CREATE {u}INDEX {iname} ON {schema}.{table} "
                   f"({', '.join(keys)}){inc};")

    return "\n".join(ddl), identity_cols


def build_gold(db, schema_sql, identity_cols, rebuild=False):
    import psycopg
    admin = psycopg.connect(host="localhost", port=5432, user="libertybee",
                            dbname="postgres", autocommit=True)
    exists = admin.execute(
        "SELECT 1 FROM pg_database WHERE datname = %s", (GOLD_DB,)).fetchone()
    if exists:
        if not rebuild:
            raise SystemExit(
                f"{GOLD_DB} already exists — rerun with --rebuild to replace it "
                f"(refusing to overwrite the baseline silently)")
        # the tool owns its own rebuild (the migration_manager --drop
        # precedent: drops route through tooling, never raw SQL in a shell)
        admin.execute(f"DROP DATABASE {GOLD_DB}")
        print(f"{GOLD_DB} dropped for rebuild")
    admin.execute(f"CREATE DATABASE {GOLD_DB}")
    admin.close()

    pg = psycopg.connect(host="localhost", port=5432, user="libertybee",
                         dbname=GOLD_DB)
    pg.execute(schema_sql)

    # data port: dbo + reference only (simulation starts empty by design),
    # loaded PARENTS-FIRST (topological over the FK graph — the alphabetical
    # order violated FK_ParamDefined_Projection on the first build attempt)
    ported = []
    raw_tables = db.execute_query(
        "SELECT s.name, t.name FROM sys.tables t "
        "JOIN sys.schemas s ON s.schema_id = t.schema_id "
        "WHERE s.name IN ('dbo','reference') ORDER BY s.name, t.name")
    fk_edges = db.execute_query(
        "SELECT SCHEMA_NAME(ct.schema_id), ct.name, SCHEMA_NAME(pt.schema_id), pt.name "
        "FROM sys.foreign_keys fk "
        "JOIN sys.tables ct ON ct.object_id = fk.parent_object_id "
        "JOIN sys.tables pt ON pt.object_id = fk.referenced_object_id "
        "WHERE SCHEMA_NAME(ct.schema_id) IN ('dbo','reference') "
        "AND SCHEMA_NAME(pt.schema_id) IN ('dbo','reference')")
    parents = {}
    for cs, ctn, ps, ptn in fk_edges:
        if (cs, ctn) != (ps, ptn):
            parents.setdefault((cs, ctn), set()).add((ps, ptn))
    tables, done = [], set()
    remaining = [(s, t) for s, t in raw_tables]
    while remaining:
        progressed = False
        for pair in list(remaining):
            if parents.get(pair, set()) <= done:
                tables.append(pair)
                done.add(pair)
                remaining.remove(pair)
                progressed = True
        if not progressed:
            raise SystemExit(f"FK cycle in reference tables: {remaining}")
    for schema, table in tables:
        cols = [r[0] for r in db.execute_query(
            "SELECT c.name FROM sys.columns c WHERE c.object_id = OBJECT_ID(?) "
            "AND c.is_computed = 0 ORDER BY c.column_id", (f"{schema}.{table}",))]
        rows = db.execute_query(
            f"SELECT {', '.join(cols)} FROM {schema}.{table}")
        if rows:
            col_list = ", ".join(cols)
            with pg.cursor().copy(
                    f"COPY {schema}.{table} ({col_list}) FROM STDIN") as copy:
                for row in rows:
                    # pyodbc yields bool for bit; PG side is smallint (see
                    # TYPE_MAP note) — convert at the boundary
                    copy.write_row(tuple(
                        int(v) if isinstance(v, bool) else v for v in row))
        ported.append((f"{schema}.{table}", len(rows)))
    pg.commit()

    # identity sequences -> beyond ported max. NOTE: unquoted DDL identifiers
    # folded to lowercase; pg_get_serial_sequence takes STRINGS, which do not
    # fold — pass them lowercased.
    for schema, table, col in identity_cols:
        pg.execute(
            f"SELECT setval(pg_get_serial_sequence("
            f"'{schema.lower()}.{table.lower()}', '{col.lower()}'), "
            f"(SELECT COALESCE(MAX({col}), 0) + 1 FROM {schema}.{table}), false)")
    pg.commit()

    # parity audit — fail loud
    print("\nPARITY AUDIT (source vs libertybee_gold):")
    ok = True
    for schema, table in tables:
        src_n = db.execute_query(f"SELECT COUNT(*) FROM {schema}.{table}")[0][0]
        dst_n = pg.execute(f"SELECT COUNT(*) FROM {schema}.{table}").fetchone()[0]
        mark = "OK " if src_n == dst_n else "FAIL"
        ok = ok and (src_n == dst_n)
        print(f"  [{mark}] {schema}.{table}: {src_n} vs {dst_n}")
    pg_tables = pg.execute(
        "SELECT COUNT(*) FROM information_schema.tables "
        "WHERE table_schema IN ('dbo','reference','simulation') "
        "AND table_type='BASE TABLE'").fetchone()[0]
    src_tables = db.execute_query(
        "SELECT COUNT(*) FROM sys.tables t JOIN sys.schemas s "
        "ON s.schema_id = t.schema_id "
        "WHERE s.name IN ('dbo','reference','simulation')")[0][0]
    print(f"  [{'OK ' if pg_tables == src_tables else 'FAIL'}] table count: "
          f"{src_tables} vs {pg_tables}")
    ok = ok and (pg_tables == src_tables)
    pg.close()
    if not ok:
        raise SystemExit("PARITY AUDIT FAILED — see above")
    print(f"\n{GOLD_DB} built; template-mint with: "
          f"CREATE DATABASE <env> TEMPLATE {GOLD_DB}")


if __name__ == "__main__":
    ap = argparse.ArgumentParser()
    ap.add_argument("--env", required=True)
    ap.add_argument("--out", default=None)
    ap.add_argument("--build-gold", action="store_true")
    ap.add_argument("--rebuild", action="store_true",
                    help="with --build-gold: replace an existing libertybee_gold")
    args = ap.parse_args()

    src = DatabaseManager(
        rf"C:\LibertyBee\environments\{args.env}\db_config.json")
    schema_sql, identity_cols = generate(src)
    out_path = args.out or os.path.join(os.path.dirname(__file__), "pg_schema.sql")
    with open(out_path, "w", encoding="utf-8", newline="\n") as f:
        f.write(schema_sql)
    print(f"schema written: {out_path} "
          f"({schema_sql.count('CREATE TABLE')} tables, {len(identity_cols)} identity cols)")
    if args.build_gold:
        build_gold(src, schema_sql, identity_cols, rebuild=args.rebuild)
